In [1]:
import numpy as np

In [2]:
my_arr=np.arange(1000000)

In [3]:
my_list=list(range(1000000))

In [6]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 34 ms


In [7]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 865 ms


In [8]:
#科塞100题
print("""hello!
      world!
      I'm coming.""")

hello!
      world!
      I'm coming.


In [ ]:
#上边为什么会有缩进？好奇怪

In [9]:
#1.导入库并改名
import numpy as np

In [15]:
#2.输出版本和配置说明
print(np.__version__)#第一次执行时没注意，这里少打了半个括号
np.show_config()#这也是个函数啊？好神奇

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [18]:
#3.创建固定长度的空向量
Z=np.zeros(10)#运行时提示了NameError: name 'z' is not defined错误,原来是print语句里的Z是小写的，又一次验证了Python是大小写敏感的
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
#4.找到数组的内存大小
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))#?为什么是800啊？我没学过数据结构...

800 bytes


In [23]:
#5.获取numpy中add函数的说明文档
np.info(np.add)#import的时候已经重命名为np了，于是numpy就不能用了。。。

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [24]:
#6.创建长度为10，第五个值为1的空向量
Z=np.zeros(10)
Z[4]=1#从0开始计数
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
#7.创建值域范围从10到100的向量
Z=np.arange(10,101)#到100，由于Python创建的是左闭右开的，因此上限要取101
print(Z)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [26]:
#8.反转一个向量
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [27]:
#9.创建一个 3乘3且值从0到8的矩阵
Z=np.arange(9).reshape(3,3)#reshape将一维数组改写成三乘三矩阵
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#9'.创建一个 3乘3且值从0到8的矩阵 另一种方法
Z=np.arange(9).reshape(-1,3)#reshape可以只指定列数，行数看着办
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
#9''.创建一个更大的矩阵 #这时如果不能整除，就会报错
Z=np.arange(703).reshape(-1,19)#reshape可以只指定列数，行数看着办
print(Z)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18]
 [ 19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37]
 [ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
   56]
 [ 57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
   75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94]
 [ 95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
  113]
 [114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
  132]
 [133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
  151]
 [152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
  170]
 [171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
  189]
 [190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
  208]
 [209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226
  227]
 [228 229 230 231 232 233 23

In [38]:
#10.找出给定数组中非零元素的位置索引
nz=np.nonzero([1,2,5,0,0,0,3,6,8,0,8,6,5,4,6,0,87,0])#注意是nonzero
print(nz)

(array([ 0,  1,  2,  6,  7,  8, 10, 11, 12, 13, 14, 16], dtype=int64),)


In [42]:
#11.创建单位矩阵
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#12.创建3乘3乘3的随机数组
print(np.random.random((3,3,3)))

[[[0.72944468 0.3415927  0.2010668 ]
  [0.52140546 0.58217496 0.27285661]
  [0.90198358 0.92910192 0.27338674]]

 [[0.99993587 0.77747776 0.22595593]
  [0.47992835 0.74388064 0.35212886]
  [0.95526863 0.10869195 0.62801276]]

 [[0.1403734  0.30480761 0.34168905]
  [0.94264113 0.48690081 0.81147968]
  [0.29635381 0.07246111 0.84094108]]]


In [44]:
#13.创建10乘10随机数组并找出最大值和最小值
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()#赋值也可以这样啊
print (Zmin,Zmax)

0.0149621375222595 0.9764094086489762


In [47]:
#14.创建给定长度的随机向量并求平均值、最大最小值
Z=np.random.random((30))
print(Z.mean(),Z.max(),Z.min())


0.4334992706709408 0.9985650991150263 0.030037230229127077


In [48]:
#15.创建二维数组，边界值为1，其余为0
Z=np.ones((10,10))
Z[1:-1,1:-1]=0#这是什么意思呢？
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
#16.对于给定数组，添加0值边界
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [53]:
#17.计算
0*np.nan#nan=not a number

nan

In [54]:
np.nan==np.nan

False

In [55]:
np.nan>np.nan

False

In [56]:
np.nan-np.nan

nan

In [57]:
0.3==3*0.1

False

In [59]:
#18.创建5乘5矩阵，并设置值1,2,3,4落在对角线下方
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [60]:
#19. 创建8乘8矩阵，设置为棋盘样式
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
#20.考虑（6,7,8）形状的数组，第100个元素的索引（x,y,z）是什么？
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
