In [12]:
#第五章
import pandas as pd
from pandas import Series,DataFrame

In [13]:
#5.1
obj=pd.Series([4,7,-5,3])

In [14]:
obj#Series字符串的形式是：左边是索引，右边是值。

0    4
1    7
2   -5
3    3
dtype: int64

In [15]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [16]:
obj.index#默认的索引使用的是range(4)

RangeIndex(start=0, stop=4, step=1)

In [18]:
obj2=pd.Series([4,7,-5,3],index=['d','b','a','c'])#使用index=[]手动指定索引
#例如清洗参考文献时，可以根据每个字段的实际含义，增加元数据字段的标签作为索引

In [19]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [20]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [21]:
obj2['a']#使用索引选取Series中的单个值

-5

In [22]:
obj2[['c','a','d','c','b']]#使用索引选取Series中的多个值，可以重复选取

c    3
a   -5
d    4
c    3
b    7
dtype: int64

In [23]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [24]:
obj2*2

d     8
b    14
a   -10
c     6
dtype: int64

In [25]:
obj2**2

d    16
b    49
a    25
c     9
dtype: int64

In [27]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [28]:
'b'in obj2

True

In [29]:
'e' in obj2

False

In [61]:
#通过Python字典中的数据来创建Series
sdata={'title':'亚纯函数涉及小函数的唯一性','author':'闫钟峰','journal':'成都信息工程学院学报','year':'2009','vol':9}

In [62]:
obj3=pd.Series(sdata)

In [63]:
obj3

title      亚纯函数涉及小函数的唯一性
author               闫钟峰
journal       成都信息工程学院学报
year                2009
vol                    9
dtype: object

In [64]:
metadata=['author','title','journal','ref']#构造新的索引

In [65]:
obj4=pd.Series(sdata,index=metadata)#将索引传递给新的Series

In [66]:
obj4

author               闫钟峰
title      亚纯函数涉及小函数的唯一性
journal       成都信息工程学院学报
ref                  NaN
dtype: object

In [67]:
pd.isnull(obj4)#isnull函数可以用于检测缺失数据

author     False
title      False
journal    False
ref         True
dtype: bool

In [68]:
pd.notnull(obj4)

author      True
title       True
journal     True
ref        False
dtype: bool

In [69]:
obj4.isnull()

author     False
title      False
journal    False
ref         True
dtype: bool

In [70]:
obj4.notnull#这是什么情况？少打了括号，但不会报错，还是会有结果？

<bound method Series.notnull of author               闫钟峰
title      亚纯函数涉及小函数的唯一性
journal       成都信息工程学院学报
ref                  NaN
dtype: object>

In [71]:
obj4.notnull()

author      True
title       True
journal     True
ref        False
dtype: bool

In [72]:
obj4.isnull#这是什么情况？少打了括号，但还是会有结果？

<bound method Series.isnull of author               闫钟峰
title      亚纯函数涉及小函数的唯一性
journal       成都信息工程学院学报
ref                  NaN
dtype: object>

In [73]:
obj3

title      亚纯函数涉及小函数的唯一性
author               闫钟峰
journal       成都信息工程学院学报
year                2009
vol                    9
dtype: object

In [74]:
obj4

author               闫钟峰
title      亚纯函数涉及小函数的唯一性
journal       成都信息工程学院学报
ref                  NaN
dtype: object

In [75]:
obj3+obj4#注意字符串相加，就是直接连接起来，但是如果一个为NaN，结果就为NaN

author                         闫钟峰闫钟峰
journal          成都信息工程学院学报成都信息工程学院学报
ref                               NaN
title      亚纯函数涉及小函数的唯一性亚纯函数涉及小函数的唯一性
vol                               NaN
year                              NaN
dtype: object

In [76]:
obj44=pd.Series(sdata,index=['author','title','year','vol','ref'])

In [77]:
obj44

author              闫钟峰
title     亚纯函数涉及小函数的唯一性
year               2009
vol                   9
ref                 NaN
dtype: object

In [79]:
obj3+obj44#如果2009没设置成字符串，而是数字，应该会相加吧？
#果然是这样，vol相加的结果是18

author                         闫钟峰闫钟峰
journal                           NaN
ref                               NaN
title      亚纯函数涉及小函数的唯一性亚纯函数涉及小函数的唯一性
vol                                18
year                         20092009
dtype: object

In [80]:
obj4.name='content'

In [82]:
obj4.index.name='metadata'

In [83]:
obj4

metadata
author               闫钟峰
title      亚纯函数涉及小函数的唯一性
journal       成都信息工程学院学报
ref                  NaN
Name: content, dtype: object

In [84]:
#Series的索引可以通过赋值的方式直接修改
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [85]:
obj.index=['Bob','Steve','Jeff','Ryan']

In [86]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [ ]:
#DataFrame

In [90]:
data={'作者':['闫钟峰','郭峰','崔海建','鲍文竹','康海刚','邹温林','秦健秋','张汉'],
      '年份':[2007,2010,2008,2008,2009,2007,2007,2008],
      '期刊':['西南大学学报','数学学报','数学物理学报','数学评论','成都信息工程学院学报','西南大学学报','四川大学学报','数学年刊'],
      '卷':[5,6,4,5,6,8,4,7]}

In [91]:
frame=pd.DataFrame(data)

In [92]:
frame

作者    年份          期刊  卷
0  闫钟峰  2007      西南大学学报  5
1   郭峰  2010        数学学报  6
2  崔海建  2008      数学物理学报  4
3  鲍文竹  2008        数学评论  5
4  康海刚  2009  成都信息工程学院学报  6
5  邹温林  2007      西南大学学报  8
6  秦健秋  2007      四川大学学报  4
7   张汉  2008        数学年刊  7

In [93]:
frame.head()#head()方法去前五行

作者    年份          期刊  卷
0  闫钟峰  2007      西南大学学报  5
1   郭峰  2010        数学学报  6
2  崔海建  2008      数学物理学报  4
3  鲍文竹  2008        数学评论  5
4  康海刚  2009  成都信息工程学院学报  6

In [95]:
pd.DataFrame(data,columns=['期刊','作者','年份'])#指定列及顺序，类似于sql的select

期刊   作者    年份
0      西南大学学报  闫钟峰  2007
1        数学学报   郭峰  2010
2      数学物理学报  崔海建  2008
3        数学评论  鲍文竹  2008
4  成都信息工程学院学报  康海刚  2009
5      西南大学学报  邹温林  2007
6      四川大学学报  秦健秋  2007
7        数学年刊   张汉  2008

In [96]:
frame2=pd.DataFrame(data,columns=['年份','作者','期刊','标题',])#传入的列不存在，则产生缺失值NaN

In [97]:
frame2

年份   作者          期刊   标题
0  2007  闫钟峰      西南大学学报  NaN
1  2010   郭峰        数学学报  NaN
2  2008  崔海建      数学物理学报  NaN
3  2008  鲍文竹        数学评论  NaN
4  2009  康海刚  成都信息工程学院学报  NaN
5  2007  邹温林      西南大学学报  NaN
6  2007  秦健秋      四川大学学报  NaN
7  2008   张汉        数学年刊  NaN

In [98]:
frame2.columns

Index(['年份', '作者', '期刊', '标题'], dtype='object')

In [99]:
frame2['作者']

0    闫钟峰
1     郭峰
2    崔海建
3    鲍文竹
4    康海刚
5    邹温林
6    秦健秋
7     张汉
Name: 作者, dtype: object

In [100]:
frame2.年份

0    2007
1    2010
2    2008
3    2008
4    2009
5    2007
6    2007
7    2008
Name: 年份, dtype: int64

In [104]:
frame2.loc[3]#和书上略有不同，需要用frame2['作者']结果的索引

年份    2008
作者     鲍文竹
期刊    数学评论
标题     NaN
Name: 3, dtype: object

In [106]:
frame2['标题']='唯一性'#通过赋值修改列的内容

In [107]:
frame2

年份   作者          期刊   标题
0  2007  闫钟峰      西南大学学报  唯一性
1  2010   郭峰        数学学报  唯一性
2  2008  崔海建      数学物理学报  唯一性
3  2008  鲍文竹        数学评论  唯一性
4  2009  康海刚  成都信息工程学院学报  唯一性
5  2007  邹温林      西南大学学报  唯一性
6  2007  秦健秋      四川大学学报  唯一性
7  2008   张汉        数学年刊  唯一性

In [108]:
#使用列表赋值，长度必须相等
frame2['标题']=['唯一性','正规族','单位圆内的唯一性','小函数','正规定则','微分多项式','整函数','值分布']

In [110]:
frame2

年份   作者          期刊        标题
0  2007  闫钟峰      西南大学学报       唯一性
1  2010   郭峰        数学学报       正规族
2  2008  崔海建      数学物理学报  单位圆内的唯一性
3  2008  鲍文竹        数学评论       小函数
4  2009  康海刚  成都信息工程学院学报      正规定则
5  2007  邹温林      西南大学学报     微分多项式
6  2007  秦健秋      四川大学学报       整函数
7  2008   张汉        数学年刊       值分布

In [111]:
frame22=pd.DataFrame(data,columns=['标题','年份','作者','期刊','卷','期','版面费'])

In [112]:
frame22

标题    年份   作者          期刊  卷    期  版面费
0  NaN  2007  闫钟峰      西南大学学报  5  NaN  NaN
1  NaN  2010   郭峰        数学学报  6  NaN  NaN
2  NaN  2008  崔海建      数学物理学报  4  NaN  NaN
3  NaN  2008  鲍文竹        数学评论  5  NaN  NaN
4  NaN  2009  康海刚  成都信息工程学院学报  6  NaN  NaN
5  NaN  2007  邹温林      西南大学学报  8  NaN  NaN
6  NaN  2007  秦健秋      四川大学学报  4  NaN  NaN
7  NaN  2008   张汉        数学年刊  7  NaN  NaN

In [114]:
frame22['版面费']=np.arange(8)

In [115]:
frame22

标题    年份   作者          期刊  卷    期  版面费
0  NaN  2007  闫钟峰      西南大学学报  5  NaN    0
1  NaN  2010   郭峰        数学学报  6  NaN    1
2  NaN  2008  崔海建      数学物理学报  4  NaN    2
3  NaN  2008  鲍文竹        数学评论  5  NaN    3
4  NaN  2009  康海刚  成都信息工程学院学报  6  NaN    4
5  NaN  2007  邹温林      西南大学学报  8  NaN    5
6  NaN  2007  秦健秋      四川大学学报  4  NaN    6
7  NaN  2008   张汉        数学年刊  7  NaN    7

In [116]:
frame22['标题']=['唯一性','正规族','单位圆内的唯一性','小函数','正规定则','微分多项式','整函数','值分布']

In [117]:
frame22

标题    年份   作者          期刊  卷    期  版面费
0       唯一性  2007  闫钟峰      西南大学学报  5  NaN    0
1       正规族  2010   郭峰        数学学报  6  NaN    1
2  单位圆内的唯一性  2008  崔海建      数学物理学报  4  NaN    2
3       小函数  2008  鲍文竹        数学评论  5  NaN    3
4      正规定则  2009  康海刚  成都信息工程学院学报  6  NaN    4
5     微分多项式  2007  邹温林      西南大学学报  8  NaN    5
6       整函数  2007  秦健秋      四川大学学报  4  NaN    6
7       值分布  2008   张汉        数学年刊  7  NaN    7

In [127]:
#使用Series赋值，会精确匹配DataFrame的索引，并将空位用缺失值NaN填充
no=pd.Series([1,2,3,4,5,6,7],index=[1,2,3,4,6,7,8])

In [128]:
frame22['期']=no

In [129]:
frame22

标题    年份   作者          期刊  卷    期  版面费
0       唯一性  2007  闫钟峰      西南大学学报  5  NaN    0
1       正规族  2010   郭峰        数学学报  6  1.0    1
2  单位圆内的唯一性  2008  崔海建      数学物理学报  4  2.0    2
3       小函数  2008  鲍文竹        数学评论  5  3.0    3
4      正规定则  2009  康海刚  成都信息工程学院学报  6  4.0    4
5     微分多项式  2007  邹温林      西南大学学报  8  NaN    5
6       整函数  2007  秦健秋      四川大学学报  4  5.0    6
7       值分布  2008   张汉        数学年刊  7  6.0    7

In [135]:
#为不存在的列赋值，会添加列并赋值
frame22['级别']=frame22.期刊=='数学学报'
#['普刊',]

In [131]:
frame22

标题    年份   作者          期刊  卷    期  版面费     级别
0       唯一性  2007  闫钟峰      西南大学学报  5  NaN    0  False
1       正规族  2010   郭峰        数学学报  6  1.0    1   True
2  单位圆内的唯一性  2008  崔海建      数学物理学报  4  2.0    2  False
3       小函数  2008  鲍文竹        数学评论  5  3.0    3  False
4      正规定则  2009  康海刚  成都信息工程学院学报  6  4.0    4  False
5     微分多项式  2007  邹温林      西南大学学报  8  NaN    5  False
6       整函数  2007  秦健秋      四川大学学报  4  5.0    6  False
7       值分布  2008   张汉        数学年刊  7  6.0    7  False

In [136]:
#使用del删除列
del frame22['级别']

In [137]:
frame22

标题    年份   作者          期刊  卷    期  版面费
0       唯一性  2007  闫钟峰      西南大学学报  5  NaN    0
1       正规族  2010   郭峰        数学学报  6  1.0    1
2  单位圆内的唯一性  2008  崔海建      数学物理学报  4  2.0    2
3       小函数  2008  鲍文竹        数学评论  5  3.0    3
4      正规定则  2009  康海刚  成都信息工程学院学报  6  4.0    4
5     微分多项式  2007  邹温林      西南大学学报  8  NaN    5
6       整函数  2007  秦健秋      四川大学学报  4  5.0    6
7       值分布  2008   张汉        数学年刊  7  6.0    7

In [138]:
frame22.columns

Index(['标题', '年份', '作者', '期刊', '卷', '期', '版面费'], dtype='object')

In [148]:
#嵌套字典
paper={'西南大学学报':{2007:1,2008:2,2009:3},'数学物理学报':{2007:2,2008:1},'数学学报':{2008:1,2010:1}}

In [149]:
frame3=pd.DataFrame(paper)

In [150]:
frame3

西南大学学报  数学物理学报  数学学报
2007     1.0     2.0   NaN
2008     2.0     1.0   1.0
2009     3.0     NaN   NaN
2010     NaN     NaN   1.0

In [151]:
frame3.T#转置（交换行与列）

2007  2008  2009  2010
西南大学学报   1.0   2.0   3.0   NaN
数学物理学报   2.0   1.0   NaN   NaN
数学学报     NaN   1.0   NaN   1.0

In [152]:
pd.DataFrame(paper,index=[2007,2008,2009])#使用index明确指定索引，能起到类似于sql中where的筛选作用

西南大学学报  数学物理学报  数学学报
2007       1     2.0   NaN
2008       2     1.0   1.0
2009       3     NaN   NaN

In [154]:
pd.DataFrame(paper,index=[2008])#使用index明确指定索引，能起到类似于sql中where的筛选作用

西南大学学报  数学物理学报  数学学报
2008       2       1     1

In [155]:
paper1={'数学物理学报':frame['数学物理学报'][:-1],'数学学报':frame3['数学学报'][:2]}

In [156]:
paper1

{'数学物理学报': 2007    2.0
 2008    1.0
 Name: 数学物理学报, dtype: float64, '数学学报': 2007    NaN
 2008    1.0
 Name: 数学学报, dtype: float64}

In [ ]:
#可以传递给DataFrame构造器的数据类型包括：二维ndarray，数组列表或元组组成的字典，numpy的结构化记录数组，
#Series构成的字典，字典构成的字典，
#字典或Series的列表，列表或元组组成的列表，另一个DataFrame，numpy的MaskArray

In [157]:
#设置DataFrame的index和columns的name属性
frame3.index.name='year';frame3.columns.name='期刊'

In [158]:
frame3

期刊    西南大学学报  数学物理学报  数学学报
year                      
2007     1.0     2.0   NaN
2008     2.0     1.0   1.0
2009     3.0     NaN   NaN
2010     NaN     NaN   1.0

In [160]:
#values属性可以返回DataFrame中的数据
frame3.values

array([[ 1.,  2., nan],
       [ 2.,  1.,  1.],
       [ 3., nan, nan],
       [nan, nan,  1.]])

In [161]:
#如果各列数据类型不统一，则值组的dtype会返回能兼容所有列的数据类型
frame2.values

array([[2007, '闫钟峰', '西南大学学报', '唯一性'],
       [2010, '郭峰', '数学学报', '正规族'],
       [2008, '崔海建', '数学物理学报', '单位圆内的唯一性'],
       [2008, '鲍文竹', '数学评论', '小函数'],
       [2009, '康海刚', '成都信息工程学院学报', '正规定则'],
       [2007, '邹温林', '西南大学学报', '微分多项式'],
       [2007, '秦健秋', '四川大学学报', '整函数'],
       [2008, '张汉', '数学年刊', '值分布']], dtype=object)

In [163]:
#索引对象
obj=pd.Series(range(3),index=['a','b','c'])

In [164]:
index=obj.index

In [165]:
index

Index(['a', 'b', 'c'], dtype='object')

In [166]:
obj

a    0
b    1
c    2
dtype: int64

In [167]:
index[1]='d'
#index对象不可变，因此不能修改，会报错“TypeError: Index does not support mutable operations”

TypeError: Index does not support mutable operations

In [169]:
labels=pd.Index(np.arange(3))

In [170]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [171]:
obj2=pd.Series([1.5,-2.5,0],index=labels)

In [172]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [173]:
obj2.index is labels

True

In [174]:
frame3

期刊    西南大学学报  数学物理学报  数学学报
year                      
2007     1.0     2.0   NaN
2008     2.0     1.0   1.0
2009     3.0     NaN   NaN
2010     NaN     NaN   1.0

In [175]:
frame3.columns

Index(['西南大学学报', '数学物理学报', '数学学报'], dtype='object', name='期刊')

In [176]:
'数学学报' in frame3.columns

True

In [179]:
'四川大学学报' in frame3.index

False

In [180]:
'四川大学学报' in frame3.columns

False

In [181]:
#pandas的Index可以包含重复标签，与python不同
dup_labels=pd.Index(['foo','foo','bar','bar'])

In [182]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [189]:
dup_labels.is_unique#is_unique检测是否有重复

False

In [190]:
dup_labels.unique()#unique()计算无重复的数组


Index(['foo', 'bar'], dtype='object')

In [ ]:
#5.2基本功能


In [ ]:
#重新索引

In [195]:
obj=pd.Series([4.5,7.3,5.4,-6,65],index=['a','c','f','e','h'])

In [192]:
obj

a     4.5
c     7.3
f     5.4
e    -6.0
m    65.0
dtype: float64

In [196]:
obj2=obj.reindex(['a','b','c','d','e','f','g','h','i'])
#reindex可以根据新索引进行重排，如果之前没有新索引的某个字段，则引入缺失值

In [197]:
obj2

a     4.5
b     NaN
c     7.3
d     NaN
e    -6.0
f     5.4
g     NaN
h    65.0
i     NaN
dtype: float64

In [198]:
obj3=pd.Series(['blue','red','dark'])

In [199]:
obj3

0    blue
1     red
2    dark
dtype: object

In [201]:
obj3.reindex(range(6),method='ffill')#ffill=fullfill,使用前向值填充

0    blue
1     red
2    dark
3    dark
4    dark
5    dark
dtype: object

In [203]:
#修改行索引和列
frame=pd.DataFrame(np.arange(9).reshape((3,3)),
                  index=['a','c','d'],
                  columns=['Ohio','Texas','California'])

In [204]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [205]:
frame2=frame.reindex(['a','b','c','d'])#通过传递一个序列重新索引各行

In [206]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [207]:
#重新索引列使用columns
states=['Texas','Utah','California']

In [209]:
frame.reindex(columns=states)#如果添加了新的不存在于原来的列名的列，会使用缺失值填充

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [212]:
frame.reindex(columns=states,fill_value=0)#使用fill_value指定缺失值的替代值

Texas  Utah  California
a      1     0           2
c      4     0           5
d      7     0           8

In [213]:
#丢弃指定轴上的项

In [214]:
obj=pd.Series(np.arange(5.),index=['a','b','c','d','e'])

In [215]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [216]:
new_obj=obj.drop('c')#丢弃索引为c的行

In [217]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [218]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [220]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['a','b','c','d'],columns=['c1','c2','c3','c4'])

In [221]:
data

c1  c2  c3  c4
a   0   1   2   3
b   4   5   6   7
c   8   9  10  11
d  12  13  14  15

In [222]:
data.drop(['b','c'])

c1  c2  c3  c4
a   0   1   2   3
d  12  13  14  15

In [228]:
data.drop('c1',axis=1)

c2  c3  c4
a   1   2   3
b   5   6   7
c   9  10  11
d  13  14  15

In [235]:
data.drop('c2',axis=1)
#('c2',axis=0)则报错，因为行里没有叫c2的。
#如果写成('c2',axis=2)也报错，因为除了行和列，没有第三个轴

c1  c3  c4
a   0   2   3
b   4   6   7
c   8  10  11
d  12  14  15

In [232]:
data.drop('c',axis=0)#axis=0表示删除行，axis=1表示删除列，前边的'c'表示具体要删除哪一行

c1  c2  c3  c4
a   0   1   2   3
b   4   5   6   7
d  12  13  14  15

In [237]:
data.drop(['c1','c3'],axis='columns')#(['a','d'],axis='columns')则会报错，因为列里没有a，d列

c2  c4
a   1   3
b   5   7
c   9  11
d  13  15

In [238]:
obj.drop('c',inplace=True)#直接删除obj的c行，修改对象，不返回新对象，小心使用，会销毁被删除的数据

In [239]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
#索引、选取和过滤

In [242]:
obj=pd.Series(np.arange(4.),index=['a','b','c','d'])#指定索引为a,b,c,d

In [243]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [244]:
obj0=pd.Series(np.arange(4.))#不指定索引，类似于numpy数组，使用整数做索引

In [245]:
obj0

0    0.0
1    1.0
2    2.0
3    3.0
dtype: float64

In [247]:
obj['b']#使用索引定位值

1.0

In [248]:
obj[1]

1.0

In [249]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [250]:
obj[['b','c','d']]#使用列表数据类型罗列索引

b    1.0
c    2.0
d    3.0
dtype: float64

In [251]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [254]:
obj[obj<=2]#支持\theta运算符进行限定

a    0.0
b    1.0
c    2.0
dtype: float64

In [256]:
obj['b':'c']#切片运算规则与之前不一样，是包含结尾的，是个闭区间

b    1.0
c    2.0
dtype: float64

In [257]:
obj['b':'c']=5#切片是视图，修改视图，会反映在原始数据上

In [258]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [259]:
data=pd.DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','NewYork'],
                 columns=['one','two','three','four'])

In [260]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [261]:
data['two']

Ohio         1
Colorado     5
Utah         9
NewYork     13
Name: two, dtype: int32

In [263]:
data.T['Ohio']#还有什么办法选择第一行？

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int32

In [264]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
NewYork      14   12

In [266]:
data[:2]#选择前两行

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [268]:
data[data['three']>5]#通过列的值来筛选行

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [269]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
NewYork   False  False  False  False

In [270]:
data[data<5]=0#筛选并修改

In [271]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [ ]:
#用loc和iloc进行选取

In [273]:
data.loc['Colorado',['two','three']]#使用轴标签loc进行索引和筛选，选择一行和多列

two      5
three    6
Name: Colorado, dtype: int32

In [275]:
data.iloc[2,[3,0,1]]
#使用iloc和整数进行选取，第一个2表示选择行序号为2（从0开始排序）的，第二个整数列表表示选择列序号为3,0,1的列

four    11
one      8
two      9
Name: Utah, dtype: int32

In [276]:
data.iloc[2]#选择第三行

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [278]:
data.iloc[2,3]

11

In [279]:
data.iloc[:,3]

Ohio         0
Colorado     7
Utah        11
NewYork     15
Name: four, dtype: int32

In [280]:
data.iloc[0:2,3]

Ohio        0
Colorado    7
Name: four, dtype: int32

In [281]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [282]:
data.iloc[:,:3][data.three>5]#使用多个条件进行筛选

one  two  three
Colorado    0    5      6
Utah        8    9     10
NewYork    12   13     14

In [283]:
data#作为对比

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
NewYork    12   13     14    15

In [284]:
data.iat[1,1]

5

In [285]:
data.at['Utah','four']

11

In [288]:
data.get_value('Utah','four')#不推荐使用

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: get_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  """Entry point for launching an IPython kernel.


11

In [ ]:
#整数索引

In [289]:
ser=pd.Series(np.arange(3.))

In [290]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [291]:
ser[-1]#报错 KeyError: -1 和Python的内置列表与元组的索引语法不一致

KeyError: -1

In [292]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [293]:
ser2=pd.Series(np.arange(3.),index=['a','b','c'])

In [294]:
ser2[-1]#由于索引已经被明确指定为字母abc了，因此使用[-1]没有歧义

2.0

In [295]:
ser[:1]#如果轴索引含有整数，数据选取总会使用标签

0    0.0
dtype: float64

In [296]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [299]:
ser.iloc[:1]

0    0.0
dtype: float64

In [ ]:
#算术运算和数据对齐

In [304]:
s1=pd.Series([5.1,6.4,-3.2,1.5],index=['a','c','d','e'])

In [305]:
s1

a    5.1
c    6.4
d   -3.2
e    1.5
dtype: float64

In [302]:
s2=pd.Series([-2.1,3.6,4.3,5,1.5],index=['a','c','e','f','g'])

In [303]:
s2

a   -2.1
c    3.6
e    4.3
f    5.0
g    1.5
dtype: float64

In [306]:
s1+s2
#相加时原来有一个缺失的，相加后就是缺失值了，相当于相加后的缺失值是原来s1和s2的缺失值的并集

a     3.0
c    10.0
d     NaN
e     5.8
f     NaN
g     NaN
dtype: float64

In [307]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [309]:
df2=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [310]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [311]:
df2

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [312]:
df1+df2#相加后，缺失值是相加前的并集

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [313]:
df1=pd.DataFrame({'A':[1,2]})

In [314]:
df2=pd.DataFrame({'B':[3,4]})

In [315]:
df1

A
0  1
1  2

In [316]:
df2

B
0  3
1  4

In [317]:
df1+df2

A   B
0 NaN NaN
1 NaN NaN

In [318]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [ ]:
#在算数方法中填充值

In [319]:
df1=pd.DataFrame(np.arange(12).reshape((3,4)),columns=list('abcd'))

In [320]:
df2=pd.DataFrame(np.arange(20).reshape((4,5)),columns=list('abcde'))

In [321]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [322]:
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [323]:
df1+df2#相加后的缺失值是相加前的缺失值的并集

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [324]:
df1.add(df2,fill_value=0)#使用add方法传入df2以及一个fill_value参数，就不会导致缺失值扩散了

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [326]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [328]:
df1.rdiv(1)#与上述等价

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [329]:
df1.sub(1)

a  b  c   d
0 -1  0  1   2
1  3  4  5   6
2  7  8  9  10

In [330]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [331]:
df1.mul(3)

a   b   c   d
0   0   3   6   9
1  12  15  18  21
2  24  27  30  33

In [332]:
df1*3

a   b   c   d
0   0   3   6   9
1  12  15  18  21
2  24  27  30  33

In [333]:
df1.pow(2)

a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

In [334]:
df1**2

a   b    c    d
0   0   1    4    9
1  16  25   36   49
2  64  81  100  121

In [335]:
df1.reindex(columns=df2.columns,fill_value=0)#重新索引，同时可新加列，fill_value用于指定填充值，以替代缺失值

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

In [336]:
df1.reindex(columns=df2.columns)

a  b   c   d   e
0  0  1   2   3 NaN
1  4  5   6   7 NaN
2  8  9  10  11 NaN

In [ ]:
#DataFrame和Series之间的运算

In [337]:
arr=np.arange(12).reshape((3,4))

In [338]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [339]:
arr[0]#第0行

array([0, 1, 2, 3])

In [340]:
arr-arr[0]#对每一行执行相减的操作，所谓的广播——broadcasting

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [341]:
arr-arr[1]

array([[-4, -4, -4, -4],
       [ 0,  0,  0,  0],
       [ 4,  4,  4,  4]])

In [342]:
new=arr[1]

In [343]:
arr-new

array([[-4, -4, -4, -4],
       [ 0,  0,  0,  0],
       [ 4,  4,  4,  4]])

In [349]:
new1=arr[1].copy()#使用copy方法创建新对象

In [350]:
new1

array([4, 5, 6, 7])

In [351]:
arr-new1#再减去时，会对每一行做减法，而不是只对对应行做减法,DataFrame与Series之间的运算大抵如此

array([[-4, -4, -4, -4],
       [ 0,  0,  0,  0],
       [ 4,  4,  4,  4]])

In [352]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [353]:
frame=pd.DataFrame(np.arange(12).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [354]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [355]:
series=frame.iloc[0]

In [356]:
series

b    0
d    1
e    2
Name: Utah, dtype: int32

In [357]:
frame-series#DataFrame和Series之间的运算，会将Series的索引匹配到DataFrame的列，然后沿着行一直向下广播

b  d  e
Utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

In [358]:
series2=pd.Series(range(3),index=['b','e','f'])

In [360]:
series2

b    0
e    1
f    2
dtype: int64

In [362]:
frame+series2#和的索引是索引的并集，如果某个索引f在frame中找不到，将会被缺失值填充

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [363]:
#匹配行且在列上广播
series3=frame['d']#选出列

In [364]:
frame

b   d   e
Utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [365]:
series3

Utah       1
Ohio       4
Texas      7
Oregon    10
Name: d, dtype: int32

In [366]:
#使用sub做减法，可以传入参数，series3表示要减去的量，axis='index'表示以index（也就是列）为轴，每一列都减去series3
frame.sub(series3,axis='index')


b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [369]:
frame.sub(series3,axis=0)#0表示以列为轴

b  d  e
Utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

In [370]:
frame.sub(series3,axis=1)
#1表示以行为轴，由于series3的索引和行的索引不一致，故索引是二者的并，且所有值都是缺失值

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [372]:
series33=frame[:1]#选择第一行

In [373]:
series33

b  d  e
Utah  0  1  2

In [374]:
#然后减去第一行
frame.sub(series33,axis=1)#结果为什么有问题？

b    d    e
Ohio    NaN  NaN  NaN
Oregon  NaN  NaN  NaN
Texas   NaN  NaN  NaN
Utah    0.0  0.0  0.0

In [375]:
#实际上直接减就行
frame-series33#结果为什么还会有问题？

b    d    e
Ohio    NaN  NaN  NaN
Oregon  NaN  NaN  NaN
Texas   NaN  NaN  NaN
Utah    0.0  0.0  0.0

In [ ]:
#函数应用和映射
#numpy的ufuncs元素级数组方法也可用于操作pandas

In [376]:
frame=pd.DataFrame(np.random.randn(4,3),columns=list('bed'),index=['Utah','Ohio','Texas','Oregon'])

In [377]:
frame

b         e         d
Utah    1.455717 -0.056005 -0.664414
Ohio    1.794505 -2.439105  1.004880
Texas   0.437415  0.460521 -0.846261
Oregon -0.726851 -1.252442 -0.926116

In [378]:
np.abs(frame)

b         e         d
Utah    1.455717  0.056005  0.664414
Ohio    1.794505  2.439105  1.004880
Texas   0.437415  0.460521  0.846261
Oregon  0.726851  1.252442  0.926116

In [380]:
f=lambda  x:x.max()-x.min()#lambda

In [381]:
f

<function __main__.<lambda>(x)>

In [382]:
frame.apply(f)

b    2.521355
e    2.899626
d    1.930996
dtype: float64

In [386]:
f=lambda x:x.max()-x.min()

In [387]:
frame.apply(f)#apply方法可以将函数应用到由各列或行所形成的一维数组上。

b    2.521355
e    2.899626
d    1.930996
dtype: float64

In [392]:
frame.T.apply(f)#对于列，先转置再使用apply方法。有没有其他实现方式？

Utah      2.120130
Ohio      4.233609
Texas     1.306782
Oregon    0.525591
dtype: float64

In [394]:
frame.apply(f,axis='columns')#与上边的执行效果一致

Utah      2.120130
Ohio      4.233609
Texas     1.306782
Oregon    0.525591
dtype: float64

In [395]:
frame.sum()#按列求和

b    2.960786
e   -3.287030
d   -1.431910
dtype: float64

In [396]:
frame.sum(axis='columns')#按行求和

Utah      0.735298
Ohio      0.360281
Texas     0.051675
Oregon   -2.905408
dtype: float64

In [397]:
frame.mean()

b    0.740196
e   -0.821757
d   -0.357977
dtype: float64

In [398]:
frame.mean(axis='columns')

Utah      0.245099
Ohio      0.120094
Texas     0.017225
Oregon   -0.968469
dtype: float64

In [ ]:
#其他还有哪些函数？

In [400]:
def f(x):
    return pd.Series([x.min(),x.max()],index=['min','max'])

In [401]:
frame.apply(f)#传递到apply的函数可以返回多个值的Series

b         e         d
min -0.726851 -2.439105 -0.926116
max  1.794505  0.460521  1.004880

In [402]:
format=lambda x:'%.2f' %x#返回两位小数的浮点值
#莫名地感觉如何定义lambda表达式是门大学问

In [403]:
frame.applymap(format)

b      e      d
Utah     1.46  -0.06  -0.66
Ohio     1.79  -2.44   1.00
Texas    0.44   0.46  -0.85
Oregon  -0.73  -1.25  -0.93

In [404]:
frame

b         e         d
Utah    1.455717 -0.056005 -0.664414
Ohio    1.794505 -2.439105  1.004880
Texas   0.437415  0.460521 -0.846261
Oregon -0.726851 -1.252442 -0.926116

In [409]:
frame['e'].map(format)#map是作用于Series的

Utah      -0.06
Ohio      -2.44
Texas      0.46
Oregon    -1.25
Name: e, dtype: object

In [418]:
frame['e']

Utah     -0.056005
Ohio     -2.439105
Texas     0.460521
Oregon   -1.252442
Name: e, dtype: float64

In [419]:
frame[:1]#map(format)#对行怎么操作？

b         e         d
Utah  1.455717 -0.056005 -0.664414

In [ ]:
#排序和排名

In [420]:
obj=pd.Series(range(4),index=['d','a','b','c'])

In [421]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [422]:
obj.sort_index()#sort_index()函数按索引重新排序

a    1
b    2
c    3
d    0
dtype: int64

In [424]:
frame=pd.DataFrame(np.arange(8).reshape((2,4)),index=['three','one'],columns=['d','a','b','c'])

In [425]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [426]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [427]:
frame.sort_index(axis=1)#使用列进行排序

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [428]:
frame.sort_index(axis=1,ascending=False)#将默认的升序排列改为降序排列

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [429]:
obj=pd.Series([4,7,-3,2])

In [431]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [432]:
obj.sort_values()#对Series排序

2   -3
3    2
0    4
1    7
dtype: int64

In [433]:
obj=pd.Series([4,np.nan,7,np.nan,3,-2])

In [434]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4    3.0
5   -2.0
dtype: float64

In [435]:
obj.sort_values()#空值默认放到最后#应该也有办法将空值改为放到最前吧？

5   -2.0
4    3.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [436]:
frame=pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [437]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [438]:
frame.sort_values(by='b')#sort_values的by选项可以选定根据哪个或哪几个列进行排序，类似于sql中的order by

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [439]:
frame.sort_values(by=['b','a'])#按多个列排序，给by传入多个列的名称

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [440]:
obj=pd.Series([7,-5,7,4,2,0,4])

In [441]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [442]:
obj.rank()#排名使用rank()函数，反馈原始值的排名，参考 https://blog.csdn.net/code_porter/article/details/86517233

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [445]:
obj.rank(method='first')#条目0和2虽然都是7，但由于标签0位于前边，就给它赋予了靠前的排名

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [446]:
obj.rank(ascending=False,method='max')#降序排名，method='max'表示如果值相同就取最大也就是靠后的排名

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [447]:
#在行或列上计算DataFrame的排名
frame=pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [448]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [449]:
frame.rank(axis='columns')#以列为轴计算排名，也就是在每一行内分别计算排名

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [ ]:
#带有重复标签的轴索引

In [450]:
obj=pd.Series(range(5),index=['a','a','b','b','c'])

In [451]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [453]:
obj.index.is_unique#检查索引的值是否唯一

False

In [454]:
obj['a']#不同的值有相同的索引，都会被选出来
#扩展，相同的值有相同的索引，会怎么样？

a    0
a    1
dtype: int64

In [456]:
obj1=pd.Series([1,2,3,3,4,5,5],index=['a','a','a','b','b','c','c'])

In [457]:
obj1

a    1
a    2
a    3
b    3
b    4
c    5
c    5
dtype: int64

In [458]:
obj1['a']#相同的值有相同的索引，会被去重

a    1
a    2
a    3
dtype: int64

In [459]:
obj['c']

4

In [460]:
#DataFrame的索引也是如此
df=pd.DataFrame(np.random.randn(4,3),index=['a','a','b','b',])

In [461]:
df

0         1         2
a  0.426322  1.952706 -2.037795
a  0.075762 -0.841552 -1.210878
b  0.919644 -2.341497 -1.750845
b -0.745307  0.013555  1.130104

In [462]:
df.loc['b']

0         1         2
b  0.919644 -2.341497 -1.750845
b -0.745307  0.013555  1.130104

In [ ]:
#5.3汇总和计算描述统计

In [466]:
df=pd.DataFrame([[1.4,np.nan],[7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                index=['a','b','c','d'],columns=['one','two'])

In [467]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [468]:
df.sum()#na值被自动排除，除非整个切片都是na值，和sql一致，count也不会计算缺失值

one    9.25
two   -5.80
dtype: float64

In [469]:
df.mean(axis='columns',skipna=False)#指定以列为轴，就是计算每一行的均值，skipna默认是True

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [470]:
df.idxmax()#找出最大的值的索引，是个间接值，类似于rank()排名返回每个位置的数值的排名

one    b
two    d
dtype: object

In [471]:
df.cumsum()#累计型的方法，按列计算累计和

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [472]:
df.cumsum(axis='columns')#指定以列为轴，就是按行计算累计和

one   two
a  1.40   NaN
b  7.10  2.60
c   NaN   NaN
d  0.75 -0.55

In [474]:
df.describe()#列出了常用的很多个统计量，默认按列统计

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [475]:
df.describe(axis='columns')#会报错，TypeError: describe() got an unexpected keyword argument 'axis'，无此参数

TypeError: describe() got an unexpected keyword argument 'axis'

In [477]:
df.T.describe()#转置后按列计算，就是转置前的按行计算的结果

a         b    c         d
count  1.0  2.000000  0.0  2.000000
mean   1.4  1.300000  NaN -0.275000
std    NaN  8.202439  NaN  1.449569
min    1.4 -4.500000  NaN -1.300000
25%    1.4 -1.600000  NaN -0.787500
50%    1.4  1.300000  NaN -0.275000
75%    1.4  4.200000  NaN  0.237500
max    1.4  7.100000  NaN  0.750000

In [478]:
obj=pd.Series(['a','a','b','c']*4)

In [479]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [480]:
obj.describe()#统计量的类型和数值型数据不同

count     16
unique     3
top        a
freq       8
dtype: object

In [481]:
df.var()

one    12.205833
two     5.120000
dtype: float64

In [482]:
df.std()

one    3.493685
two    2.262742
dtype: float64

In [485]:
df.median()#不加括号不会报错，但是结果不一样

one    1.4
two   -2.9
dtype: float64

In [487]:
df.skew()#偏度

one    1.664846
two         NaN
dtype: float64

In [488]:
df.kurt()#峰度

one   NaN
two   NaN
dtype: float64

In [489]:
df.mad()#定义是什么？

one    2.677778
two    1.600000
dtype: float64

In [493]:
df.mad??#查看mad函数的代码发现，是根据平均值计算的平均绝对离差

In [ ]:
#相关系数与协方差

In [494]:
import pandas_datareader.data as web

ModuleNotFoundError: No module named 'pandas_datareader'

In [495]:
conda list#检查发现没装pandas_datareader
#回到命令行使用pip install pandas-datareader 命令安装

# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0  
alabaster                 0.7.12                   py36_0  
anaconda                  custom           py36h363777c_0  
anaconda-client           1.7.2                    py36_0  
anaconda-navigator        1.9.7                    py36_0  
anaconda-project          0.8.2                    py36_0  
asn1crypto                0.24.0                   py36_0  
astroid                   2.2.5                    py36_0  
astropy                   3.2.1            py36he774522_0  
atomicwrites              1.3.0                    py36_1  
attrs                     19.1.0                   py36_1  
babel                     2.7.0                      py_0  
backcall                  0.1.0                    py36_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5   

In [496]:
import pandas_datareader.data as web

In [498]:
all_data=({ticker:web.get_data_yahoo(ticker)
         for ticker in ['AAPL','IBM','MSFT','GOOG']})

In [499]:
price=pd.DataFrame(({ticker:data['Adj Close']
                    for ticker,data in all_data.items()}))

In [503]:
volume=pd.DataFrame({ticker:data['Volume']
                    for ticker,data in all_data.items()})

In [508]:
all_data#AttributeError: 'dict' object has no attribute 'head' ,怎么才能只显示字典的前五行？

{'AAPL':                   High         Low        Open       Close       Volume  \
 Date                                                                      
 2009-12-31   30.478571   30.080000   30.447144   30.104286   88102700.0   
 2010-01-04   30.642857   30.340000   30.490000   30.572857  123432400.0   
 2010-01-05   30.798571   30.464285   30.657143   30.625713  150476200.0   
 2010-01-06   30.747143   30.107143   30.625713   30.138571  138040000.0   
 2010-01-07   30.285715   29.864286   30.250000   30.082857  119282800.0   
 2010-01-08   30.285715   29.865715   30.042856   30.282858  111902700.0   
 2010-01-11   30.428572   29.778572   30.400000   30.015715  115557400.0   
 2010-01-12   29.967142   29.488571   29.884285   29.674286  148614900.0   
 2010-01-13   30.132856   29.157143   29.695715   30.092857  151473000.0   
 2010-01-14   30.065714   29.860001   30.015715   29.918571  108223500.0   
 2010-01-15   30.228571   29.410000   30.132856   29.418571  148516900.0   
 201

In [506]:
price.head()

AAPL        IBM       MSFT        GOOG
Date                                                   
2009-12-31  26.372231  98.137283  24.152580  307.986847
2010-01-04  26.782711  99.299347  24.525019  311.349976
2010-01-05  26.829010  98.099792  24.532942  309.978882
2010-01-06  26.402260  97.462532  24.382378  302.164703
2010-01-07  26.353460  97.125160  24.128809  295.130463

In [509]:
returns=price.pct_change()#计算价格的百分数变化

In [510]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2019-06-19 -0.002923  0.005133  0.003921 -0.001151
2019-06-20  0.008036  0.012912  0.009286  0.008246
2019-06-21 -0.003409  0.002521  0.000146  0.009411
2019-06-24 -0.001006  0.001078  0.005914 -0.005669
2019-06-25 -0.015158 -0.007104 -0.031572 -0.026149

In [512]:
returns['MSFT'].corr(returns['IBM'])#使用corr方法计算相关系数
#由于相关系数是两组数据之间的关系，因此要分别提取两列出来，类似于矩阵的点乘 a.dot(b)的形式

0.4870579333972048

In [514]:
returns['MSFT'].cov(returns['IBM'])#计算协方差(标准化后就是相关系数)

8.680743356886965e-05

In [515]:
returns.corr()#DataFrame的corr方法返回所有两两之间的相关系数矩阵

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.379376  0.453093  0.461116
IBM   0.379376  1.000000  0.487058  0.403112
MSFT  0.453093  0.487058  1.000000  0.538028
GOOG  0.461116  0.403112  0.538028  1.000000

In [516]:
returns.cov()#道理同上

AAPL       IBM      MSFT      GOOG
AAPL  0.000266  0.000076  0.000107  0.000116
IBM   0.000076  0.000152  0.000087  0.000077
MSFT  0.000107  0.000087  0.000209  0.000120
GOOG  0.000116  0.000077  0.000120  0.000239

In [517]:
returns.corrwith(returns.IBM)#corrwith方法可以计算DataFrame中各列与另外一个Series的相关系数

AAPL    0.379376
IBM     1.000000
MSFT    0.487058
GOOG    0.403112
dtype: float64

In [520]:
returns.IBM#len(returns.IBM)#实际上可以构造另外一个2386个数值，且时间一致的序列，去与returns各列计算内相关系数

Date
2009-12-31         NaN
2010-01-04    0.011841
2010-01-05   -0.012080
2010-01-06   -0.006496
2010-01-07   -0.003462
2010-01-08    0.010035
2010-01-11   -0.010470
2010-01-12    0.007955
2010-01-13   -0.002145
2010-01-14    0.015972
2010-01-15   -0.004006
2010-01-19    0.017908
2010-01-20   -0.028999
2010-01-21   -0.009597
2010-01-22   -0.027132
2010-01-25    0.004940
2010-01-26   -0.002934
2010-01-27    0.004612
2010-01-28   -0.020423
2010-01-29   -0.010990
2010-02-01    0.018629
2010-02-02    0.006898
2010-02-03    0.001036
2010-02-04   -0.021168
2010-02-05    0.004227
2010-02-08   -0.008864
2010-02-09    0.010912
2010-02-10   -0.003246
2010-02-11    0.007492
2010-02-12    0.002182
                ...   
2019-05-14    0.014381
2019-05-15    0.008176
2019-05-16    0.011012
2019-05-17   -0.011481
2019-05-20    0.005956
2019-05-21    0.009843
2019-05-22   -0.000733
2019-05-23   -0.029043
2019-05-24   -0.000831
2019-05-28   -0.013759
2019-05-29   -0.005902
2019-05-30   -0.000925
2019-0

In [521]:
returns.corrwith(volume)#传入一个DataFrame，由于列名一致，则会按照列名配对计算相关系数。
#volume是成交量，因此计算的是百分比变化returns和成交量volume的相关系数

AAPL   -0.061945
IBM    -0.156114
MSFT   -0.089885
GOOG   -0.020494
dtype: float64

In [522]:
volume

AAPL         IBM         MSFT        GOOG
Date                                                        
2009-12-31   88102700.0   4223400.0   31929700.0   2455400.0
2010-01-04  123432400.0   6155300.0   38409100.0   3937800.0
2010-01-05  150476200.0   6841400.0   49749600.0   6048500.0
2010-01-06  138040000.0   5605300.0   58182400.0   8009000.0
2010-01-07  119282800.0   5840600.0   50559700.0  12912000.0
2010-01-08  111902700.0   4197200.0   51197400.0   9509900.0
2010-01-11  115557400.0   5730400.0   68754700.0  14519600.0
2010-01-12  148614900.0   8081500.0   65912100.0   9769600.0
2010-01-13  151473000.0   6455400.0   51863500.0  13077600.0
2010-01-14  108223500.0   7111800.0   63228100.0   8535300.0
2010-01-15  148516900.0   8494400.0   79913200.0  10939600.0
2010-01-19  182501900.0  13916200.0   46575700.0   8689500.0
2010-01-20  153038200.0  15197500.0   54849500.0   6543600.0
2010-01-21  152038600.0   9608600.0   73086700.0  12697400.0
2010-01-22  220441900.0  10088600.0  102004600.0  13689200.0
2010-01-25  266424900.0   5738500.0   63373000.0   8897200.0
2010-01-26  466777500.0   7135300.0   66639900.0   8767600.0
2010-01-27  430642100.0   8719200.0   63949500.0   7980200.0
2010-01-28  293375600.0   9622200.0  117513700.0   6500100.0
2010-01-29  311488100.0  11571200.0  193888500.0   8334700.0
2010-02-01  187469100.0   7242900.0   85931100.0   4530800.0
2010-02-02  174585600.0   5899900.0   54413700.0   8245600.0
2010-02-03  153832000.0   4177100.0   61397900.0   6037000.0
2010-02-04  189413000.0   9126900.0   77850000.0   6799200.0
2010-02-05  212576700.0   8617000.0   80960100.0   6353000.0
2010-02-08  119567700.0   5718500.0   52820600.0   5423500.0
2010-02-09  158221700.0   6044500.0   59195800.0   5675700.0
2010-02-10   92590400.0   5219100.0   48591300.0   5383700.0
2010-02-11  137586400.0   5089000.0   65993700.0   4851300.0
2010-02-12  163867200.0   8017700.0   81117200.0   4589000.0
...                 ...         ...          ...         ...
2019-05-14   36529700.0   3280400.0   25266300.0   1836600.0
2019-05-15   26544700.0   2551000.0   24722700.0   2289300.0
2019-05-16   33031400.0   3017300.0   30112200.0   1531400.0
2019-05-17   32879100.0   2619100.0   25770500.0   1208600.0
2019-05-20   38612300.0   3264500.0   23706900.0   1353300.0
2019-05-21   28364800.0   2503500.0   15293300.0   1159800.0
2019-05-22   29748600.0   1849800.0   15396500.0    914500.0
2019-05-23   36529700.0   5343400.0   23603800.0   1198900.0
2019-05-24   23714700.0   2596100.0   14123400.0   1112000.0
2019-05-28   27948200.0   4908800.0   23128400.0   1365000.0
2019-05-29   28481200.0   3679000.0   22763100.0   1538200.0
2019-05-30   21218400.0   2741900.0   16829600.0    951900.0
2019-05-31   27043600.0   3539300.0   26646800.0   1507800.0
2019-06-03   40396100.0   4266900.0   37983600.0   5130600.0
2019-06-04   30968000.0   3913500.0   29382600.0   2833500.0
2019-06-05   29773400.0   3161300.0   24926100.0   2168400.0
2019-06-06   22526300.0   2298200.0   21459000.0   1703200.0
2019-06-07   30684400.0   2553400.0   33885600.0   1802400.0
2019-06-10   26220900.0   2911300.0   26477100.0   1464200.0
2019-06-11   26932900.0   3407300.0   23913700.0   1436700.0
2019-06-12   18253200.0   2254700.0   17092500.0   1061000.0
2019-06-13   21674600.0   2955300.0   17200800.0   1057700.0
2019-06-14   18761500.0   2193300.0   17821700.0   1111500.0
2019-06-17   14651700.0   2194100.0   14496200.0    941600.0
2019-06-18   26551000.0   2914700.0   25934500.0   1386700.0
2019-06-19   21124200.0   2382400.0   23744400.0   1338800.0
2019-06-20   21514000.0   3071000.0   33042600.0   1262000.0
2019-06-21   47800600.0   5288700.0   36727900.0   1947600.0
2019-06-24   18205500.0   2186000.0   20619300.0   1395600.0
2019-06-25   21070334.0   2798511.0   29599336.0   1546913.0

[2386 rows x 4 columns]

In [524]:
returns.corrwith(volume,axis='columns')
#传入参数axis='columns'表示按行计算相关系数，尽管这么做对这批数据好像没有明显意义

Date
2009-12-31         NaN
2010-01-04    0.791567
2010-01-05    0.737318
2010-01-06    0.016919
2010-01-07    0.507385
2010-01-08   -0.779525
2010-01-11   -0.351052
2010-01-12   -0.288883
2010-01-13    0.886223
2010-01-14   -0.492766
2010-01-15   -0.290268
2010-01-19    0.903181
2010-01-20    0.281733
2010-01-21   -0.695781
2010-01-22   -0.247710
2010-01-25    0.801913
2010-01-26    0.866178
2010-01-27    0.793796
2010-01-28   -0.903431
2010-01-29   -0.965122
2010-02-01    0.102698
2010-02-02    0.407185
2010-02-03    0.411516
2010-02-04   -0.943248
2010-02-05    0.890385
2010-02-08   -0.362191
2010-02-09    0.452481
2010-02-10   -0.320461
2010-02-11    0.833537
2010-02-12    0.597521
                ...   
2019-05-14    0.592564
2019-05-15   -0.445317
2019-05-16   -0.198790
2019-05-17    0.968626
2019-05-20   -0.667382
2019-05-21    0.641491
2019-05-22   -0.738932
2019-05-23    0.119768
2019-05-24    0.166984
2019-05-28    0.234091
2019-05-29    0.533626
2019-05-30    0.889925
2019-0

In [ ]:
#唯一值、值计算以及成员资格

In [525]:
obj=pd.Series(['c','a','d','a','a','b','b','c','c'])

In [526]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [527]:
obj.unique()#从一维的Series中提取唯一值的方法，返回的值未排序

array(['c', 'a', 'd', 'b'], dtype=object)

In [528]:
obj.value_counts()#计算每个值的出现次数，结果是按照频次从大到小排序了的。

a    3
c    3
b    2
d    1
dtype: int64

In [530]:
pd.value_counts(obj.values,sort=False)#value_counts是一个pandas顶级方法，可用于任何数组或序列

b    2
c    3
d    1
a    3
dtype: int64

In [531]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [532]:
mask=obj.isin(['b','c'])#isin用于判断矢量化集合的成员资格，可以用于过滤Series或DataFrame的列中的数据的子集

In [533]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [534]:
obj[mask]#选出属于mask的obj的分量

0    c
5    b
6    b
7    c
8    c
dtype: object

In [538]:
to_match=pd.Series(['c','a','b','b','c','a','f'])

In [539]:
unique_vals=pd.Series(['c','b','a'])

In [540]:
pd.Index(unique_vals).get_indexer(to_match)
#Index.get_indexer方法给出to_match中的元素在unique_vals中的索引,不在则索引为-1

array([ 0,  2,  1,  1,  0,  2, -1], dtype=int64)

In [543]:
data=pd.DataFrame({'qu1':[1,3,4,3,4],'qu2':[2,3,1,2,3],'qu3':[1,5,2,4,4]},)

In [544]:
data

qu1  qu2  qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [545]:
result=data.apply(pd.value_counts).fillna(0)

In [546]:
result
#结果中的行标签是所有列的唯一值，后边的频率表示该值在该列的出现频率

qu1  qu2  qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0