In [63]:
import numpy as np

In [64]:
my_arr=np.arange(1000000)

In [65]:
my_list=list(range(1000000))

In [66]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 32 ms


In [67]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 923 ms


In [68]:
#科塞100题
print("""hello!
      world!
      I'm coming.""")

hello!
      world!
      I'm coming.


In [69]:
#上边为什么会有缩进？好奇怪

In [70]:
#1.导入库并改名
import numpy as np

In [71]:
#2.输出版本和配置说明
print(np.__version__)#第一次执行时没注意，这里少打了半个括号
np.show_config()#这也是个函数啊？好神奇

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [72]:
#3.创建固定长度的空向量
Z=np.zeros(10)#运行时提示了NameError: name 'z' is not defined错误,原来是print语句里的Z是小写的，又一次验证了Python是大小写敏感的
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [73]:
#4.找到数组的内存大小
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))#?为什么是800啊？我没学过数据结构...

800 bytes


In [74]:
#5.获取numpy中add函数的说明文档
np.info(np.add)#import的时候已经重命名为np了，于是numpy就不能用了。。。

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [75]:
#6.创建长度为10，第五个值为1的空向量
Z=np.zeros(10)
Z[4]=1#从0开始计数
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [76]:
#7.创建值域范围从10到100的向量
Z=np.arange(10,101)#到100，由于Python创建的是左闭右开的，因此上限要取101
print(Z)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [77]:
#8.反转一个向量
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [78]:
#9.创建一个 3乘3且值从0到8的矩阵
Z=np.arange(9).reshape(3,3)#reshape将一维数组改写成三乘三矩阵
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
#9'.创建一个 3乘3且值从0到8的矩阵 另一种方法
Z=np.arange(9).reshape(-1,3)#reshape可以只指定列数，行数看着办
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [80]:
#9''.创建一个更大的矩阵 #这时如果不能整除，就会报错
Z=np.arange(703).reshape(-1,19)#reshape可以只指定列数，行数看着办
print(Z)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18]
 [ 19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37]
 [ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
   56]
 [ 57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
   75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94]
 [ 95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
  113]
 [114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
  132]
 [133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
  151]
 [152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
  170]
 [171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
  189]
 [190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
  208]
 [209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226
  227]
 [228 229 230 231 232 233 23

In [81]:
#10.找出给定数组中非零元素的位置索引
nz=np.nonzero([1,2,5,0,0,0,3,6,8,0,8,6,5,4,6,0,87,0])#注意是nonzero
print(nz)

(array([ 0,  1,  2,  6,  7,  8, 10, 11, 12, 13, 14, 16], dtype=int64),)


In [82]:
#11.创建单位矩阵
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [83]:
#12.创建3乘3乘3的随机数组
print(np.random.random((3,3,3)))

[[[0.80562886 0.64513    0.30158973]
  [0.34552486 0.45086393 0.66913187]
  [0.02592093 0.01249612 0.69706584]]

 [[0.03967487 0.20959604 0.97979243]
  [0.22759276 0.56121001 0.70797498]
  [0.47951998 0.85424896 0.76817791]]

 [[0.81150737 0.30026036 0.32632873]
  [0.32417393 0.17040797 0.41474287]
  [0.85246425 0.91537884 0.15601463]]]


In [84]:
#13.创建10乘10随机数组并找出最大值和最小值
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()#赋值也可以这样啊
print (Zmin,Zmax)

0.0006670801526186265 0.9901207325635548


In [85]:
#14.创建给定长度的随机向量并求平均值、最大最小值
Z=np.random.random((30))
print(Z.mean(),Z.max(),Z.min())


0.41361472182691517 0.9286885967862559 0.0003267915907702035


In [86]:
#15.创建二维数组，边界值为1，其余为0
Z=np.ones((10,10))
Z[1:-1,1:-1]=0#这是什么意思呢？
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [87]:
#16.对于给定数组，添加0值边界
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [88]:
#17.计算
0*np.nan#nan=not a number

nan

In [89]:
np.nan==np.nan

False

In [90]:
np.nan>np.nan

False

In [91]:
np.nan-np.nan

nan

In [92]:
0.3==3*0.1

False

In [93]:
#18.创建5乘5矩阵，并设置值1,2,3,4落在对角线下方
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [94]:
#19. 创建8乘8矩阵，设置为棋盘样式
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [95]:
#20.考虑（6,7,8）形状的数组，第100个元素的索引（x,y,z）是什么？
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [96]:
#21.用title函数创建8乘8的棋盘样式矩阵
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
#22.对5乘5随机矩阵归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.16886864 0.71252662 0.61891944 0.44032625 0.28443179]
 [1.         0.70983949 0.00437339 0.34807091 0.53807347]
 [0.32336759 0.         0.24387959 0.34197049 0.13216782]
 [0.08390243 0.9204955  0.8411657  0.03085535 0.13309234]
 [0.22727999 0.72498043 0.726158   0.29414297 0.28301138]]


In [98]:
#23.创建一个将颜色描述成（RGBA）四个无符号字节的自定义dtype
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [99]:
#24.5乘3矩阵与3乘2矩阵相乘的结果
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [100]:
#25.给定一维数组，对其在3到8之间的元素取反
Z=np.arange(15)
print(Z)#增加对比
Z[(3<Z)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [101]:
#26.执行脚本的结果是什么？
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))#为什么会不一样？参https://blog.csdn.net/lyl771857509/article/details/84047421

9
10


In [102]:
#26'.numpy的sum函数与Python的sum函数的区别
a = array([[1, 2, 3], [4, 5, 6]])
# Python自带sum函数相加
SUM = sum(a)  # 所有元素求和
SUM_0 = sum(a, 0)  # 按照列求和
SUM_1 = sum(a, 1)  # 按照行求和
print("SUM:"+str(SUM))
print("SUM_0:"+str(SUM_0))
print("SUM_1:"+str(SUM_1))
 
# numpy中sum函数相加
np_SUM = np.sum(a)  # 所有元素求和
print("np_SUM:"+str(np_SUM))
np_SUM_0 = np.sum(a, axis=0)  # 按照列求和
print("np_SUM_0:"+str(np_SUM_0))
np_SUM_1 = np.sum(a, axis=1)  # 按照行求和
print("np_SUM_1:"+str(np_SUM_1))
#--------------------- 
#作者：DL&CV_study 
#来源：CSDN 
#原文：https://blog.csdn.net/Sophia_11/article/details/84975009 
#版权声明：本文为博主原创文章，转载请附上博文链接！

SUM:21
SUM_0:[5 7 9]
SUM_1:[ 6 15]
np_SUM:21
np_SUM_0:[5 7 9]
np_SUM_1:[ 6 15]


In [103]:
#27.对于整数向量Z，如下表达式合法的有哪些？
Z = np.arange(5)
Z ** Z # 向量也可以做幂运算


array([  1,   1,   4,  27, 256], dtype=int32)

In [104]:
Z = np.arange(5)
2 << Z >> 2  # false#<<右移运算符，这个为什么不合法？

array([0, 1, 2, 4, 8], dtype=int32)

In [105]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [106]:
Z = np.arange(5)
print(Z)
1j*Z   # legal#??

[0 1 2 3 4]


array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [107]:
Z = np.arange(5)
print(Z)
Z/1/1   # legal

[0 1 2 3 4]


array([0., 1., 2., 3., 4.])

In [109]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [111]:
#28.表达式的结果
print(np.array(0) / np.array(0))#除数是0，结果not a number
print(np.array(0) // np.array(0))#整除
print(np.array([np.nan]).astype(int).astype(float))#astype()函数转换arry中的数据类型

nan
0
[-2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [112]:
#29.从零位对浮点数做舍入
Z=np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[ 7.40843463 -9.91471512 -0.95333075  4.47176957  6.8230166   0.10340737
 -3.11870387  1.82534031  7.78815898 -2.91217779]
[  8. -10.  -1.   5.   7.   1.  -4.   2.   8.  -3.]


In [114]:
#30.找出两个数组中的共同元素
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))
print(np.intersectld(Z1,Z2))#为什么手动敲的就不对？迷


[4 7 3 1 8 4 5 4 7 0]
[2 6 8 9 0 2 1 9 2 1]
[0 1 8]


AttributeError: module 'numpy' has no attribute 'intersectld'

In [115]:
#31.如何忽略所有numpy警告？
#这道题还是补做了，我怕我会忍不住....

In [116]:
#32.表达式是否正确？
np.sqrt(-1) == np.emath.sqrt(-1)  # False 负一开什么根号啊？

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [117]:
#33.如何得到昨天、今天与明天的日期？
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


Yesterday is 2019-06-22
Today is 2019-06-23
Tomorrow is 2019-06-24


In [118]:
#34.输出2016年7月的所有日期
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [119]:
#35.如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)


array([3., 3., 3.])

In [120]:
np.divide(A,2,out=A)


array([0.5, 0.5, 0.5])

In [121]:
np.negative(A,out=A)


array([-0.5, -0.5, -0.5])

In [122]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [123]:
#36.提取随机数组整数部分的五种方法——回字的五种写法
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)

[4.79780552 0.73891906 5.88811658 6.57829842 2.71961308 9.95559265
 8.15399929 7.8427482  2.18249133 6.49291119]
[4. 0. 5. 6. 2. 9. 8. 7. 2. 6.]


In [124]:
print(Z)
print (np.floor(Z))

[4.79780552 0.73891906 5.88811658 6.57829842 2.71961308 9.95559265
 8.15399929 7.8427482  2.18249133 6.49291119]
[4. 0. 5. 6. 2. 9. 8. 7. 2. 6.]


In [125]:
print(Z)
print (np.ceil(Z)-1)

[4.79780552 0.73891906 5.88811658 6.57829842 2.71961308 9.95559265
 8.15399929 7.8427482  2.18249133 6.49291119]
[4. 0. 5. 6. 2. 9. 8. 7. 2. 6.]


In [126]:
print (Z.astype(int))#这个好。。。

[4 0 5 6 2 9 8 7 2 6]


In [127]:
print (np.trunc(Z))#trunc函数在sql里也常用

[4. 0. 5. 6. 2. 9. 8. 7. 2. 6.]


In [128]:
#37.5乘5矩阵，每行数值的范围为0到4
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [129]:
#38.定义一个可生成十个整数的函数，然后构建一个数组
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [130]:
#39.创建长度为十的随机向量，值域为零一开区间
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [131]:
#40.创建长度为十的随机向量并排序
Z=np.random.random(10)
print(Z)
Z.sort()#使用sort函数排序
print(Z)

[0.51442306 0.94105004 0.7115517  0.77857055 0.87854372 0.20434572
 0.50505956 0.60263368 0.30232068 0.56087812]
[0.20434572 0.30232068 0.50505956 0.51442306 0.56087812 0.60263368
 0.7115517  0.77857055 0.87854372 0.94105004]


In [132]:
#41.小数组求和，如何比np.sum更快？
Z = np.arange(23)
%time np.sum(Z)

Wall time: 0 ns


253

In [133]:
%time np.add.reduce(Z)#为什么时间会一样？

Wall time: 0 ns


253

In [134]:
Z = np.random.randn(13)
print(Z)
Z = np.array(Z)
print(Z)
%time sum(Z)


[-0.06345132  0.23357278  0.959749   -0.27404653 -0.77834663 -2.37670466
 -0.2628079   0.35060243  0.53044153  2.07125581  0.47139581 -0.57161536
  1.61819015]
[-0.06345132  0.23357278  0.959749   -0.27404653 -0.77834663 -2.37670466
 -0.2628079   0.35060243  0.53044153  2.07125581  0.47139581 -0.57161536
  1.61819015]
Wall time: 0 ns


1.9082351047684116

In [135]:
%time np.sum(Z)

Wall time: 0 ns


1.9082351047684116

In [136]:
%time np.add.reduce(Z)#0是几个意思？还需要研究

Wall time: 0 ns


1.9082351047684116

In [137]:
#42.检验两个随机数组是否相等
A = np.random.randint(0,2,5)
print(A)
B = np.random.randint(0,2,5)
print(B)
C=A
print(C)

[0 1 0 1 0]
[0 0 1 0 0]
[0 1 0 1 0]


In [138]:
equal = np.allclose(A,B)#结果为布尔值
print(equal)

False


In [139]:
equal = np.allclose(A,C)#结果为布尔值
print(equal)

True


In [140]:
#43.创建只读数组
Z = np.zeros(10)
Z.flags.writeable = False#不可修改
Z[0] = 1

ValueError: assignment destination is read-only

In [141]:
#44.将笛卡尔坐标下的十乘二矩阵转换为极坐标形式
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
print("X=",X)
print("Y=",Y)
R = np.sqrt(X**2+Y**2)#
T = np.arctan2(Y,X)#反正切求辐角
print ("R=",R)
print ("T=",T)

X= [0.38428726 0.36589871 0.58152925 0.11310527 0.66326367 0.37084184
 0.48214574 0.56407832 0.12084874 0.7849163 ]
Y= [0.98131561 0.82484047 0.2279559  0.77110917 0.49901674 0.11900912
 0.67874414 0.51335484 0.17122847 0.48639027]
R= [1.05387714 0.90235451 0.62461201 0.7793601  0.83002193 0.38946995
 0.83256118 0.7627041  0.20957959 0.92340083]
T= [1.19754865 1.1532779  0.37358554 1.42515619 0.64501335 0.31053374
 0.95315793 0.73835482 0.95620516 0.55475841]


In [142]:
#45.创建长度为10的向量，并将向量中最大值替换为1
Z=np.random.random(10)
print(Z)
Z[Z.argmax()]=1
print(Z)

[0.00473177 0.08249391 0.87595726 0.61555502 0.56646821 0.5500494
 0.55664619 0.14909617 0.32276855 0.1219056 ]
[0.00473177 0.08249391 1.         0.61555502 0.56646821 0.5500494
 0.55664619 0.14909617 0.32276855 0.1219056 ]


In [143]:
#46.创建结构化数组，并实现x,y左表覆盖[0,1]*[0,1]区域
Z=np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y']=np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [144]:
#47.给定两个数组X,Y，构造柯西矩阵C(C_ij=1/x_i-y_i)
X = np.arange(10)
Y = np.arange(10)
Z = X + 0.5
C = 1.0 / np.subtract.outer(X, Z)
D = 1.0 / np.subtract.outer(X, Y)
print(X)
print(Y)
print(Z)
print("C=",C)
print("D=",D)
print(np.linalg.det(C))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5 8.5 9.5]
C= [[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333 -0.11764706 -0.10526316]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615 -0.13333333 -0.11764706]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818 -0.15384615 -0.13333333]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222 -0.18181818 -0.15384615]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429 -0.22222222 -0.18181818]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4     

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [145]:
#48.打印每个numpy标量类型的最小值和最大值
 for dtype in [np.int8, np.int32, np.int64]:
     print(np.iinfo(dtype).min)
     print(np.iinfo(dtype).max)

IndentationError: unexpected indent (<ipython-input-145-81250fc6d796>, line 2)

In [146]:
 for dtype in [np.float32, np.float64]:
     print(np.finfo(dtype).min)
     print(np.finfo(dtype).max)
     print(np.finfo(dtype).eps)

-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [147]:
#49.打印一个数组中的所有数值#?? 有问题
np.set_printoptions(threshold=np.nan)
Z=np.random.random((16,16))
print(Z)
np.set_printoptions(threshold=np.inf)
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

In [148]:
#50.给定标量时，如何找到数组中最接近标量的值？
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print(v)
index = (np.abs(Z-v)).argmin()
print (Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
61.68997080875216
62


In [149]:
#51. 创建一个表示位置(x,y)和颜色(r,g,b)的结构化数组
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print (Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


In [150]:
#52.对表示形状（100,2)的随机向量，找到点与点的距离
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print (D)

[[0.         0.26445881 0.42631844 0.2797539  0.85524779 0.24621822
  0.63377241 0.24657728 0.05881904 0.31908655]
 [0.26445881 0.         0.3329069  0.47955678 0.70097622 0.50583358
  0.37047363 0.43394417 0.30316141 0.35099462]
 [0.42631844 0.3329069  0.         0.70540066 0.43166297 0.56912805
  0.46533609 0.66920311 0.48510105 0.17663357]
 [0.2797539  0.47955678 0.70540066 0.         1.13197548 0.31128896
  0.83458467 0.04728457 0.22103414 0.59242286]
 [0.85524779 0.70097622 0.43166297 1.13197548 0.         0.99310843
  0.57931657 1.09336233 0.91368475 0.58735887]
 [0.24621822 0.50583358 0.56912805 0.31128896 0.99310843 0.
  0.86933152 0.31547934 0.23204178 0.40614261]
 [0.63377241 0.37047363 0.46533609 0.83458467 0.57931657 0.86933152
  0.         0.78748479 0.67353897 0.59976212]
 [0.24657728 0.43394417 0.66920311 0.04728457 1.09336233 0.31547934
  0.78748479 0.         0.18900229 0.56376387]
 [0.05881904 0.30316141 0.48510105 0.22103414 0.91368475 0.23204178
  0.67353897 0.18900

In [151]:
#53.将32位的浮点数转换为对应的整数
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [152]:
#54.读取文件


In [153]:
#55.np数组与enumerate等价的操作是什么？
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print (index, value)
for index in np.ndindex(Z.shape):
    print (index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [154]:
#56.生成一个通用的二维Gaussian-like数组
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print (G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [156]:
#57.如何在二维数组内部随机放置p个元素？
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print (Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [159]:
#58.减去一个矩阵中的每一行的平均值
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.42934667 -0.27362583  0.013222   -0.18728974  0.06035143  0.43464782
   0.31315068 -0.15293752  0.04362698  0.17820086]
 [-0.37907616 -0.37828084 -0.20674379  0.29800101 -0.43885375  0.33755402
   0.14073058  0.0326851   0.33563639  0.25834744]
 [-0.33278252  0.12138259  0.2691889   0.0281881   0.37219542 -0.31765745
  -0.38965793  0.14634417  0.48196512 -0.37916641]
 [ 0.48254916 -0.41647612 -0.30761541 -0.20063973  0.50695536 -0.23899411
  -0.00534619  0.29076059 -0.38322652  0.27203298]
 [-0.40554664  0.38270134 -0.3017988   0.00572237 -0.20177329  0.23040628
   0.48517317  0.46178626 -0.43046168 -0.226209  ]]


In [160]:
# 方法2
Y = X - X.mean(axis=1).reshape(-1, 1)
print (Y)

[[-0.42934667 -0.27362583  0.013222   -0.18728974  0.06035143  0.43464782
   0.31315068 -0.15293752  0.04362698  0.17820086]
 [-0.37907616 -0.37828084 -0.20674379  0.29800101 -0.43885375  0.33755402
   0.14073058  0.0326851   0.33563639  0.25834744]
 [-0.33278252  0.12138259  0.2691889   0.0281881   0.37219542 -0.31765745
  -0.38965793  0.14634417  0.48196512 -0.37916641]
 [ 0.48254916 -0.41647612 -0.30761541 -0.20063973  0.50695536 -0.23899411
  -0.00534619  0.29076059 -0.38322652  0.27203298]
 [-0.40554664  0.38270134 -0.3017988   0.00572237 -0.20177329  0.23040628
   0.48517317  0.46178626 -0.43046168 -0.226209  ]]


In [161]:
#59.过第n列对数组进行排序
Z = np.random.randint(0,10,(3,3))
print (Z)
print (Z[Z[:,1].argsort()])

[[0 8 4]
 [2 2 1]
 [7 6 1]]
[[2 2 1]
 [7 6 1]
 [0 8 4]]


In [162]:
#60.如何检查二维数组是否有空列
Z=np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


In [163]:
#61.从数组中的给定值中找出最近的值
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print (m)

0.5563390780933596


In [164]:
#62.用迭代器(iterator)计算两个分别具有形状(1,3)和(3,1)的数组
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
print (it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [165]:
#63.创建具有name属性的数组类
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [166]:
#64.对给定向量
Z=np.ones(10)
I=np.random.randint(0,len(Z),20)
Z+=np.bincount(I, minlength=len(Z))
print(Z)

[3. 3. 3. 1. 2. 4. 6. 3. 3. 2.]


In [167]:
#方法二
np.add.at(Z, I, 1)
print(Z)

[ 5.  5.  5.  1.  3.  7. 11.  5.  5.  3.]


In [168]:
#65.根据索引列表将向量的元素累加到数组
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print (F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [171]:
#66. 考虑一个(dtype=ubyte) 的 (w,h,3)图像，计算其唯一颜色的数量
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print (n)



8


In [172]:
#67. 考虑一个四维数组，如何一次性计算出最后两个轴(axis)的和？ 
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print (sum)



[[46 69 48 53]
 [67 56 68 45]
 [54 71 56 63]]


In [173]:
# 方法2
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print (sum)

[[46 69 48 53]
 [67 56 68 45]
 [54 71 56 63]]


In [174]:
#68. 考虑一个一维向量D，如何使用相同大小的向量S来计算D子集的均值？
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print (D_means)



[0.54455876 0.67127673 0.49924847 0.53177327 0.67135754 0.52500208
 0.4363891  0.62143096 0.5434076  0.51828886]


In [175]:
# 方法2
import pandas as pd#pandas
print(pd.Series(D).groupby(S).mean())

0    0.544559
1    0.671277
2    0.499248
3    0.531773
4    0.671358
5    0.525002
6    0.436389
7    0.621431
8    0.543408
9    0.518289
dtype: float64


In [178]:
#69. 如何获得点积 dot prodcut的对角线?
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))
#%time np.diag(np.dot(A, B))



array([0.7985787 , 0.99136904, 0.82407208, 1.53933504, 2.04784296])

In [180]:
# 方法2
np.sum(A * B.T, axis=1)

array([0.7985787 , 0.99136904, 0.82407208, 1.53933504, 2.04784296])

In [181]:
# 方法3
np.einsum("ij,ji->i", A, B)

array([0.7985787 , 0.99136904, 0.82407208, 1.53933504, 2.04784296])

In [183]:
#70. 对于向量[1,2,3,4,5],建立新的向量，在这个新向量中每个值之间有3个连续的零？
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print (Z0)



[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [188]:
#71. 考虑一个维度(5,5,3)的数组，如何将其与一个(5,5)的数组相乘？
A = np.ones((5,5,3))
print("A=",A)
B = 2*np.ones((5,5))
print("B=",B)
print ("A * B=",A * B[:,:,None])



A= [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
B= [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
A * B= [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [189]:
#72. 如何对一个数组中任意两行做交换? 
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print (A)



[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [190]:
#73. 考虑一个可以描述10个三角形的triplets，找到可以分割全部三角形的line segment

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print (G)



[( 0, 42) ( 0, 78) ( 4, 27) ( 4, 77) ( 5,  7) ( 5, 72) ( 7, 72) (10, 55)
 (10, 78) (19, 26) (19, 83) (22, 46) (22, 61) (26, 83) (27, 77) (36, 49)
 (36, 61) (40, 66) (40, 69) (42, 78) (46, 61) (49, 61) (55, 78) (57, 61)
 (57, 66) (61, 66) (62, 85) (62, 94) (66, 69) (85, 94)]


In [191]:
#74. 给定一个二进制的数组C，如何产生一个数组A满足np.bincount(A)==C
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print (A)



[1 1 2 3 4 4 6]


In [192]:
#75. 如何通过滑动窗口计算一个数组的平均数? 
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))



[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [194]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)

print (Z)



[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [195]:
#77. 如何对布尔值取反，或者原位(in-place)改变浮点数的符号(sign)？
Z = np.random.randint(0,2,100)
print(Z)
np.logical_not(Z, out=Z)




[0 1 0 1 1 1 1 0 0 0 0 0 0 1 0 1 0 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 0 1 0 0 0
 0 1 1 0 1 0 0 0 1 0 1 0 0 1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0
 1 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 0]


array([1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [197]:
Z = np.random.uniform(-1.0,1.0,100)
print(Z)
np.negative(Z, out=Z)

[ 0.35040296  0.28670369 -0.22726981 -0.91078031  0.7889617  -0.0030759
  0.2717473   0.83196521 -0.64178006 -0.3154238   0.59882978 -0.59867537
 -0.55349415 -0.52105231 -0.47853452  0.99655352 -0.69408613  0.93489644
  0.64381491  0.76876556 -0.56169012 -0.61410839  0.49356388 -0.39970073
  0.66310625 -0.82029501  0.51406647 -0.90298912 -0.87520685 -0.37441765
 -0.8475918  -0.57986583  0.40923363 -0.62463575  0.2030641   0.23948373
 -0.67314324  0.13946974  0.29725753  0.83621557  0.53254691  0.39263811
  0.70981009  0.26049799  0.54014958  0.91277762 -0.59022631  0.9500936
  0.78321005 -0.72683455  0.32058262  0.71141101  0.43833342  0.17771285
 -0.67680446  0.96070888 -0.73406248  0.53594764 -0.50702259 -0.82513048
  0.3130383   0.59653872 -0.78238866  0.60355719 -0.61692726 -0.16181172
 -0.19406789  0.63904837  0.64830095 -0.98001234 -0.22267251  0.15639545
 -0.14381069 -0.33444202  0.72260367  0.43087172 -0.01107751  0.90706084
  0.66316011  0.60468878 -0.62785364  0.78140282 -0.9

array([-0.35040296, -0.28670369,  0.22726981,  0.91078031, -0.7889617 ,
        0.0030759 , -0.2717473 , -0.83196521,  0.64178006,  0.3154238 ,
       -0.59882978,  0.59867537,  0.55349415,  0.52105231,  0.47853452,
       -0.99655352,  0.69408613, -0.93489644, -0.64381491, -0.76876556,
        0.56169012,  0.61410839, -0.49356388,  0.39970073, -0.66310625,
        0.82029501, -0.51406647,  0.90298912,  0.87520685,  0.37441765,
        0.8475918 ,  0.57986583, -0.40923363,  0.62463575, -0.2030641 ,
       -0.23948373,  0.67314324, -0.13946974, -0.29725753, -0.83621557,
       -0.53254691, -0.39263811, -0.70981009, -0.26049799, -0.54014958,
       -0.91277762,  0.59022631, -0.9500936 , -0.78321005,  0.72683455,
       -0.32058262, -0.71141101, -0.43833342, -0.17771285,  0.67680446,
       -0.96070888,  0.73406248, -0.53594764,  0.50702259,  0.82513048,
       -0.3130383 , -0.59653872,  0.78238866, -0.60355719,  0.61692726,
        0.16181172,  0.19406789, -0.63904837, -0.64830095,  0.98

In [198]:
#78. 考虑两组点集P0和P1去描述一组线(二维)和一个点p,如何计算点p到每一条线 i (P0[i],P1[i])的距离？
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print (distance(P0, P1, p))


[ 9.79848123  6.11874831  3.32501786  2.5068641   7.51135178  0.32641616
  1.92520119  1.32381966 11.76679562  6.93942879]


In [199]:
#79.考虑两组点集P0和P1去描述一组线(二维)和一组点集P，如何计算每一个点 j(P[j]) 到每一条线 i (P0[i],P1[i])的距离？
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print (np.array([distance(P0,P1,p_i) for p_i in p]))



[[ 9.53446515  0.06314562 13.6598637  11.45543812  9.50566764  2.97761623
   9.86763541  7.10462609  0.09037468  2.97386136]
 [ 4.47998765 13.01087612  4.13472602  2.53811478  3.8353839   2.2460435
   0.12563105  5.69853942  1.67233602  3.09903143]
 [ 1.91595885  9.4782783   0.96854565  8.02225158  2.32525503  4.44727817
   4.89495268  9.10008555  5.0130861   3.09392727]
 [ 7.30588806  0.46576954  2.4014327  15.52083847  1.64090135  6.85572523
   1.36406496  3.10662968  8.76138434  9.24112445]
 [ 9.18517106  0.06033499 11.50751825 12.31084547  7.3509114   1.04969501
   7.72191576  5.17882714  1.65927669  4.24400105]
 [ 3.84894227  4.80611081  6.79658696  9.5255134   4.05202181  0.30996989
   2.93521992  0.60576187  2.06974815  2.73638443]
 [ 9.36604955  0.47019224  9.49256477 13.62906605  5.17624983  1.07288668
   5.72319295  3.55031716  3.6770687   5.90937948]
 [ 1.13197781 10.54183339 10.08185915  2.60218639  9.05044092  6.08234573
   6.10150546  0.44068731  4.72469541  4.3737423 ]
 

In [200]:
#80.Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary) (★★★)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print (Z)
print (R)



[[8 8 6 8 4 9 5 0 9 9]
 [0 7 7 2 6 2 8 3 4 1]
 [5 2 1 2 5 4 3 9 0 2]
 [0 3 0 4 4 5 7 6 1 8]
 [1 3 1 4 5 4 4 6 5 5]
 [9 8 9 1 6 0 3 0 7 5]
 [1 7 1 9 8 3 0 7 7 5]
 [8 4 9 2 8 1 3 6 7 0]
 [7 6 2 6 9 2 8 7 8 0]
 [6 5 8 9 9 1 3 2 4 5]]
[[0 0 0 0 0]
 [0 8 8 6 8]
 [0 0 7 7 2]
 [0 5 2 1 2]
 [0 0 3 0 4]]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [201]:
#81. 考虑一个数组Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14],如何生成一个数组R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ...,[11,12,13,14]]? 
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print (R)



[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [202]:
#82. 计算一个矩阵的秩
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print (rank)



10


In [203]:
#83. 如何找到一个数组中出现频率最高的值？
Z = np.random.randint(0,10,50)
print (np.bincount(Z).argmax())



3


In [204]:
#84. 从一个10x10的矩阵中提取出连续的3x3区块
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)#??
print (C)



[[[[2 3 3]
   [1 1 3]
   [2 2 1]]

  [[3 3 4]
   [1 3 2]
   [2 1 4]]

  [[3 4 4]
   [3 2 0]
   [1 4 1]]

  [[4 4 1]
   [2 0 3]
   [4 1 3]]

  [[4 1 4]
   [0 3 3]
   [1 3 2]]

  [[1 4 3]
   [3 3 1]
   [3 2 2]]

  [[4 3 2]
   [3 1 1]
   [2 2 1]]

  [[3 2 2]
   [1 1 0]
   [2 1 3]]]


 [[[1 1 3]
   [2 2 1]
   [0 4 1]]

  [[1 3 2]
   [2 1 4]
   [4 1 1]]

  [[3 2 0]
   [1 4 1]
   [1 1 2]]

  [[2 0 3]
   [4 1 3]
   [1 2 2]]

  [[0 3 3]
   [1 3 2]
   [2 2 1]]

  [[3 3 1]
   [3 2 2]
   [2 1 0]]

  [[3 1 1]
   [2 2 1]
   [1 0 1]]

  [[1 1 0]
   [2 1 3]
   [0 1 2]]]


 [[[2 2 1]
   [0 4 1]
   [4 3 4]]

  [[2 1 4]
   [4 1 1]
   [3 4 3]]

  [[1 4 1]
   [1 1 2]
   [4 3 1]]

  [[4 1 3]
   [1 2 2]
   [3 1 3]]

  [[1 3 2]
   [2 2 1]
   [1 3 4]]

  [[3 2 2]
   [2 1 0]
   [3 4 3]]

  [[2 2 1]
   [1 0 1]
   [4 3 3]]

  [[2 1 3]
   [0 1 2]
   [3 3 1]]]


 [[[0 4 1]
   [4 3 4]
   [3 0 4]]

  [[4 1 1]
   [3 4 3]
   [0 4 4]]

  [[1 1 2]
   [4 3 1]
   [4 4 2]]

  [[1 2 2]
   [3 1 3]
   [4 2 3]]

  [[2 2 1]
   

In [205]:
#

In [206]:
#85. 创建一个满足 Z[i,j] == Z[j,i]的子类
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print (S)



[[ 4 11 11  3 11]
 [11  6 11  7  6]
 [11 11  8 42 14]
 [ 3  7 42  4  1]
 [11  6 14  1  2]]


In [32]:
#

In [210]:
#86. 考虑p个 nxn 矩阵和一组形状为(n,1)的向量，如何直接计算p个矩阵的乘积(n,1)？
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print (S)



[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


In [34]:
#

In [211]:
#87. 对于一个16x16的数组，如何得到一个区域(block-sum)的和(区域大小为4x4)? 
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print (S)



[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [212]:
#88. 如何利用numpy数组实现Game of Life? 
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print (Z)



[[0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [213]:
#89. 如何找到一个数组的第n个最大值? 
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argsort(Z)[-n:]])



[9995 9996 9997 9998 9999]


In [214]:
# 方法2
# 较快
print (Z[np.argpartition(-Z,n)[:n]])

[9996 9997 9999 9998 9995]


In [39]:
#

In [215]:
#90. 给定任意个数向量，创建笛卡尔积(每一个元素的每一种组合)
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix
print (cartesian(([1, 2, 3], [4, 5], [6, 7])))



[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [216]:
#91. 如何从一个正常数组创建记录数组(record array)? 
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print (R)



[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [217]:
#92. 考虑一个大向量Z, 用三种不同的方法计算它的立方
x = np.random.rand()
np.power(x,3)



0.030461055681506397

In [218]:
# 方法2
x*x*x

0.030461055681506397

In [238]:
# 方法3
np.einsum('i,i,i->i',x,x,x)#？？

array([ 0.00000000e+00,  9.85087246e-04,  7.53107070e-03,  2.35414312e-02,
        5.00086518e-02,  8.44839027e-02,  1.21435457e-01,  1.53465099e-01,
        1.73148981e-01,  1.75098102e-01,  1.57728605e-01,  1.24218435e-01,
        8.22160139e-02,  4.20528768e-02,  1.34734566e-02,  1.19458595e-03,
       -1.01973468e-04, -1.05085879e-02, -6.83997491e-02, -2.31758607e-01,
       -5.76540446e-01, -1.19161212e+00, -2.17025076e+00, -3.59870344e+00,
       -5.54283590e+00, -8.03435753e+00, -1.10584274e+01, -1.45445589e+01,
       -1.83626048e+01, -2.23252098e+01, -2.61974773e+01, -2.97137726e+01,
       -3.26006553e+01, -3.46040110e+01, -3.55176514e+01, -3.52100968e+01,
       -3.36460345e+01, -3.08991413e+01, -2.71535775e+01, -2.26924920e+01,
       -1.78732305e+01, -1.30904967e+01, -8.73030541e+00, -5.11900807e+00,
       -2.47277764e+00, -8.53539056e-01, -1.37309531e-01, -1.97408996e-04,
        7.40854178e-02,  7.63327938e-01,  2.85308261e+00,  7.16323517e+00,
        1.44605622e+01,  

In [223]:
#93. 考虑两个形状分别为(8,3) 和(2,2)的数组A和B. 如何在数组A中找到满足包含B中元素的行？(不考虑B中每行元素顺序)？ 
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print (rows)



[2 4 5 6]


In [241]:
#94. 考虑一个10乘3的矩阵，分解出有不全相同值的行 (如 [2,2,3]) 
Z = np.random.randint(0,5,(10,3))
print (Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print (U)



[[1 0 1]
 [0 4 4]
 [0 4 2]
 [0 0 0]
 [4 0 4]
 [4 0 2]
 [0 1 2]
 [0 2 0]
 [1 0 1]
 [3 1 1]]
[[1 0 1]
 [0 4 4]
 [0 4 2]
 [4 0 4]
 [4 0 2]
 [0 1 2]
 [0 2 0]
 [1 0 1]
 [3 1 1]]


In [225]:
# 方法2
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print (U)

[[4 0 4]
 [4 4 3]
 [0 0 2]
 [4 0 3]
 [1 4 0]
 [1 4 4]
 [0 1 1]
 [0 3 4]
 [3 3 4]
 [1 4 2]]


In [226]:
#95. 将一个整数向量转换为matrix binary的表现形式 
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])



[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [240]:
# 方法2
print(np.unpackbits(I[:, np.newaxis],axis=1))

TypeError: Expected an input array of unsigned byte data type

In [229]:
#96. 给定一个二维数组，如何提取出唯一的(unique)行?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print (uZ)



[[0 0 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]]


In [230]:
#97. 考虑两个向量A和B，写出用einsum等式对应的inner, outer, sum, mul函数
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
print ('sum')
print (np.einsum('i->', A))# np.sum(A)



sum
5.374074044575163


In [231]:
print ('A * B')
print (np.einsum('i,i->i', A, B)) # A * B

A * B
[0.80772444 0.48310919 0.01106023 0.12907983 0.12804494 0.14545837
 0.32224186 0.00689369 0.04052391 0.28947308]


In [232]:
print ('inner')
print (np.einsum('i,i', A, B))    # np.inner(A, B)

inner
2.3636095257412726


In [233]:
print ('outer')
print (np.einsum('i,j->ij', A, B))    # np.outer(A, B)

outer
[[0.80772444 0.44199385 0.04692068 0.20243746 0.17512043 0.19160283
  0.47031062 0.064429   0.05375807 0.65412889]
 [0.88286092 0.48310919 0.05128536 0.22126869 0.19141056 0.20942619
  0.51406005 0.07042234 0.05875877 0.71497754]
 [0.19039826 0.10418759 0.01106023 0.04771892 0.0412797  0.04516496
  0.11086247 0.01518732 0.01267195 0.15419244]
 [0.51502785 0.28182772 0.02991795 0.12907983 0.11166172 0.12217136
  0.29988329 0.04108174 0.03427766 0.417091  ]
 [0.59059371 0.32317802 0.03430757 0.14801866 0.12804494 0.14009657
  0.34388274 0.04710933 0.03930694 0.47828738]
 [0.61319699 0.33554673 0.03562059 0.15368365 0.13294549 0.14545837
  0.35704387 0.04891231 0.0408113  0.49659246]
 [0.55342707 0.30284011 0.03214856 0.13870371 0.11998695 0.13128016
  0.32224186 0.0441447  0.03683332 0.44818829]
 [0.08642384 0.04729188 0.00502036 0.02166014 0.01873731 0.02050087
  0.05032168 0.00689369 0.00575194 0.06998963]
 [0.60887894 0.33318386 0.03536976 0.15260143 0.13200931 0.14443407
  0.35

In [234]:
#98. 考虑一个由两个向量描述的路径(X,Y)，如何用等距样例(equidistant samples)对其进行采样(sample)? 
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [235]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print (X[M])



[[2. 0. 1. 1.]]


In [236]:
#100. 对于一个一维数组X，计算它boostrapped之后的95%置信区间的平均值。
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print (confint)



[-0.35773015  0.04210373]
