In [2]:
import numpy as np

In [3]:
my_arr=np.arange(1000000)

In [4]:
my_list=list(range(1000000))

In [6]:
%time for _ in range(10):my_arr2=my_arr*2

Wall time: 34 ms


In [7]:
%time for _ in range(10):my_list2=[x*2 for x in my_list]

Wall time: 865 ms


In [8]:
#科塞100题
print("""hello!
      world!
      I'm coming.""")

hello!
      world!
      I'm coming.


In [ ]:
#上边为什么会有缩进？好奇怪

In [9]:
#1.导入库并改名
import numpy as np

In [15]:
#2.输出版本和配置说明
print(np.__version__)#第一次执行时没注意，这里少打了半个括号
np.show_config()#这也是个函数啊？好神奇

1.16.4
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib'

In [18]:
#3.创建固定长度的空向量
Z=np.zeros(10)#运行时提示了NameError: name 'z' is not defined错误,原来是print语句里的Z是小写的，又一次验证了Python是大小写敏感的
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
#4.找到数组的内存大小
Z=np.zeros((10,10))
print("%d bytes"%(Z.size*Z.itemsize))#?为什么是800啊？我没学过数据结构...

800 bytes


In [23]:
#5.获取numpy中add函数的说明文档
np.info(np.add)#import的时候已经重命名为np了，于是numpy就不能用了。。。

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [24]:
#6.创建长度为10，第五个值为1的空向量
Z=np.zeros(10)
Z[4]=1#从0开始计数
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [25]:
#7.创建值域范围从10到100的向量
Z=np.arange(10,101)#到100，由于Python创建的是左闭右开的，因此上限要取101
print(Z)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


In [26]:
#8.反转一个向量
Z=np.arange(50)
Z=Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [27]:
#9.创建一个 3乘3且值从0到8的矩阵
Z=np.arange(9).reshape(3,3)#reshape将一维数组改写成三乘三矩阵
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
#9'.创建一个 3乘3且值从0到8的矩阵 另一种方法
Z=np.arange(9).reshape(-1,3)#reshape可以只指定列数，行数看着办
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
#9''.创建一个更大的矩阵 #这时如果不能整除，就会报错
Z=np.arange(703).reshape(-1,19)#reshape可以只指定列数，行数看着办
print(Z)

[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18]
 [ 19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
   37]
 [ 38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55
   56]
 [ 57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74
   75]
 [ 76  77  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93
   94]
 [ 95  96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112
  113]
 [114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131
  132]
 [133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150
  151]
 [152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169
  170]
 [171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188
  189]
 [190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
  208]
 [209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226
  227]
 [228 229 230 231 232 233 23

In [38]:
#10.找出给定数组中非零元素的位置索引
nz=np.nonzero([1,2,5,0,0,0,3,6,8,0,8,6,5,4,6,0,87,0])#注意是nonzero
print(nz)

(array([ 0,  1,  2,  6,  7,  8, 10, 11, 12, 13, 14, 16], dtype=int64),)


In [42]:
#11.创建单位矩阵
print(np.eye(3))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
#12.创建3乘3乘3的随机数组
print(np.random.random((3,3,3)))

[[[0.72944468 0.3415927  0.2010668 ]
  [0.52140546 0.58217496 0.27285661]
  [0.90198358 0.92910192 0.27338674]]

 [[0.99993587 0.77747776 0.22595593]
  [0.47992835 0.74388064 0.35212886]
  [0.95526863 0.10869195 0.62801276]]

 [[0.1403734  0.30480761 0.34168905]
  [0.94264113 0.48690081 0.81147968]
  [0.29635381 0.07246111 0.84094108]]]


In [44]:
#13.创建10乘10随机数组并找出最大值和最小值
Z=np.random.random((10,10))
Zmin,Zmax=Z.min(),Z.max()#赋值也可以这样啊
print (Zmin,Zmax)

0.0149621375222595 0.9764094086489762


In [47]:
#14.创建给定长度的随机向量并求平均值、最大最小值
Z=np.random.random((30))
print(Z.mean(),Z.max(),Z.min())


0.4334992706709408 0.9985650991150263 0.030037230229127077


In [48]:
#15.创建二维数组，边界值为1，其余为0
Z=np.ones((10,10))
Z[1:-1,1:-1]=0#这是什么意思呢？
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [50]:
#16.对于给定数组，添加0值边界
Z=np.ones((5,5))
Z=np.pad(Z,pad_width=1,mode='constant',constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [53]:
#17.计算
0*np.nan#nan=not a number

nan

In [54]:
np.nan==np.nan

False

In [55]:
np.nan>np.nan

False

In [56]:
np.nan-np.nan

nan

In [57]:
0.3==3*0.1

False

In [59]:
#18.创建5乘5矩阵，并设置值1,2,3,4落在对角线下方
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [60]:
#19. 创建8乘8矩阵，设置为棋盘样式
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [61]:
#20.考虑（6,7,8）形状的数组，第100个元素的索引（x,y,z）是什么？
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [7]:
#21.用title函数创建8乘8的棋盘样式矩阵
Z=np.tile(np.array([[0,1],[1,0]]),(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
#22.对5乘5随机矩阵归一化
Z=np.random.random((5,5))
Zmax,Zmin=Z.max(),Z.min()
Z=(Z-Zmin)/(Zmax-Zmin)
print(Z)

[[0.75254572 0.77169459 0.36094908 0.99037733 0.11077233]
 [0.30351582 0.42098631 0.21045437 0.79003526 0.14405819]
 [0.44276075 0.86952525 1.         0.07415213 0.55279747]
 [0.         0.22008173 0.75007944 0.69441657 0.72571133]
 [0.58700362 0.91795024 0.23321411 0.56984814 0.10083157]]


In [12]:
#23.创建一个将颜色描述成（RGBA）四个无符号字节的自定义dtype
color=np.dtype([("r",np.ubyte,1),
                ("g",np.ubyte,1),
                ("b",np.ubyte,1),
                ("a",np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [16]:
#24.5乘3矩阵与3乘2矩阵相乘的结果
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [23]:
#25.给定一维数组，对其在3到8之间的元素取反
Z=np.arange(15)
print(Z)#增加对比
Z[(3<Z)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


In [24]:
#26.执行脚本的结果是什么？
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))#为什么会不一样？参https://blog.csdn.net/lyl771857509/article/details/84047421

9
10


In [26]:
#26'.numpy的sum函数与Python的sum函数的区别
a = array([[1, 2, 3], [4, 5, 6]])
# Python自带sum函数相加
SUM = sum(a)  # 所有元素求和
SUM_0 = sum(a, 0)  # 按照列求和
SUM_1 = sum(a, 1)  # 按照行求和
print("SUM:"+str(SUM))
print("SUM_0:"+str(SUM_0))
print("SUM_1:"+str(SUM_1))
 
# numpy中sum函数相加
np_SUM = np.sum(a)  # 所有元素求和
print("np_SUM:"+str(np_SUM))
np_SUM_0 = np.sum(a, axis=0)  # 按照列求和
print("np_SUM_0:"+str(np_SUM_0))
np_SUM_1 = np.sum(a, axis=1)  # 按照行求和
print("np_SUM_1:"+str(np_SUM_1))
#--------------------- 
#作者：DL&CV_study 
#来源：CSDN 
#原文：https://blog.csdn.net/Sophia_11/article/details/84975009 
#版权声明：本文为博主原创文章，转载请附上博文链接！

SUM:21
SUM_0:[5 7 9]
SUM_1:[ 6 15]
np_SUM:21
np_SUM_0:[5 7 9]
np_SUM_1:[ 6 15]


In [31]:
#27.对于整数向量Z，如下表达式合法的有哪些？
Z = np.arange(5)
Z ** Z # 向量也可以做幂运算


array([  1,   1,   4,  27, 256], dtype=int32)

In [32]:
Z = np.arange(5)
2 << Z >> 2  # false#<<右移运算符，这个为什么不合法？

array([0, 1, 2, 4, 8], dtype=int32)

In [33]:
Z = np.arange(5)
Z <- Z   # legal

array([False, False, False, False, False])

In [36]:
Z = np.arange(5)
print(Z)
1j*Z   # legal#??

[0 1 2 3 4]


array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [38]:
Z = np.arange(5)
print(Z)
Z/1/1   # legal

[0 1 2 3 4]


array([0., 1., 2., 3., 4.])

In [39]:
Z = np.arange(5)
Z<Z>Z    # false

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [41]:
#28.表达式的结果
print(np.array(0) / np.array(0))#除数是0，结果not a number
print(np.array(0) // np.array(0))#整除
print(np.array([np.nan]).astype(int).astype(float))#astype()函数转换arry中的数据类型

nan
0
[-2.14748365e+09]


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [43]:
#29.从零位对浮点数做舍入
Z=np.random.uniform(-10,+10,10)
print(Z)
print(np.copysign(np.ceil(np.abs(Z)),Z))

[-4.31882482 -8.13713112 -2.55360128  6.45132856  8.82265968 -6.73359973
 -4.96155214  3.83892407 -0.43440556 -5.53925111]
[-5. -9. -3.  7.  9. -7. -5.  4. -1. -6.]


In [49]:
#30.找出两个数组中的共同元素
Z1=np.random.randint(0,10,10)
Z2=np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))
print(np.intersectld(Z1,Z2))#为什么手动敲的就不对？迷


[8 4 0 5 7 8 1 2 9 5]
[4 1 3 9 6 1 6 7 2 3]
[1 2 4 7 9]


AttributeError: module 'numpy' has no attribute 'intersectld'

In [ ]:
#31.如何忽略所有numpy警告？
#这道题还是补做了，我怕我会忍不住....

In [50]:
#32.表达式是否正确？
np.sqrt(-1) == np.emath.sqrt(-1)  # False 负一开什么根号啊？

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [51]:
#33.如何得到昨天、今天与明天的日期？
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))


Yesterday is 2019-06-20
Today is 2019-06-21
Tomorrow is 2019-06-22


In [53]:
#34.输出2016年7月的所有日期
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [55]:
#35.如何直接在位计算(A+B)\*(-A/2)(不建立副本)?
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)


array([3., 3., 3.])

In [56]:
np.divide(A,2,out=A)


array([0.5, 0.5, 0.5])

In [57]:
np.negative(A,out=A)


array([-0.5, -0.5, -0.5])

In [58]:
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [61]:
#36.提取随机数组整数部分的五种方法——回字的五种写法
Z = np.random.uniform(0,10,10)
print(Z)
print (Z - Z%1)

[5.17070545 1.68739986 5.09636429 3.06734613 0.71875813 2.31333926
 7.96319744 4.93628203 4.03149388 3.37229181]
[5. 1. 5. 3. 0. 2. 7. 4. 4. 3.]


In [63]:
print(Z)
print (np.floor(Z))

[5.17070545 1.68739986 5.09636429 3.06734613 0.71875813 2.31333926
 7.96319744 4.93628203 4.03149388 3.37229181]
[5. 1. 5. 3. 0. 2. 7. 4. 4. 3.]


In [64]:
print(Z)
print (np.ceil(Z)-1)

[5.17070545 1.68739986 5.09636429 3.06734613 0.71875813 2.31333926
 7.96319744 4.93628203 4.03149388 3.37229181]
[5. 1. 5. 3. 0. 2. 7. 4. 4. 3.]


In [66]:
print (Z.astype(int))#这个好。。。

[5 1 5 3 0 2 7 4 4 3]


In [67]:
print (np.trunc(Z))#trunc函数在sql里也常用

[5. 1. 5. 3. 0. 2. 7. 4. 4. 3.]


In [69]:
#37.5乘5矩阵，每行数值的范围为0到4
Z=np.zeros((5,5))
Z+=np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [71]:
#38.定义一个可生成十个整数的函数，然后构建一个数组
def generate():
    for x in range(10):
        yield x
Z=np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [72]:
#39.创建长度为十的随机向量，值域为零一开区间
Z=np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [74]:
#40.创建长度为十的随机向量并排序
Z=np.random.random(10)
print(Z)
Z.sort()#使用sort函数排序
print(Z)

[0.03310445 0.55495003 0.77145445 0.9182862  0.96139127 0.83329763
 0.57403188 0.90919238 0.02348453 0.8661232 ]
[0.02348453 0.03310445 0.55495003 0.57403188 0.77145445 0.83329763
 0.8661232  0.90919238 0.9182862  0.96139127]


In [ ]:
#41